// Code generated by protoc-gen-go. DO NOT EDIT.
// source: password_service.proto

package ie_gmit_ps

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HashRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashRequest) Reset()         { *m = HashRequest{} }
func (m *HashRequest) String() string { return proto.CompactTextString(m) }
func (*HashRequest) ProtoMessage()    {}
func (*HashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c0e1401011a1e2b, []int{0}
}

func (m *HashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashRequest.Unmarshal(m, b)
}
func (m *HashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashRequest.Marshal(b, m, deterministic)
}
func (m *HashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashRequest.Merge(m, src)
}
func (m *HashRequest) XXX_Size() int {
	return xxx_messageInfo_HashRequest.Size(m)
}
func (m *HashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HashRequest proto.InternalMessageInfo

func (m *HashRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HashRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type HashResponse struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	HashedPassword       []byte   `protobuf:"bytes,2,opt,name=hashedPassword,proto3" json:"hashedPassword,omitempty"`
	Salt                 []byte   `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashResponse) Reset()         { *m = HashResponse{} }
func (m *HashResponse) String() string { return proto.CompactTextString(m) }
func (*HashResponse) ProtoMessage()    {}
func (*HashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c0e1401011a1e2b, []int{1}
}

func (m *HashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashResponse.Unmarshal(m, b)
}
func (m *HashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashResponse.Marshal(b, m, deterministic)
}
func (m *HashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashResponse.Merge(m, src)
}
func (m *HashResponse) XXX_Size() int {
	return xxx_messageInfo_HashResponse.Size(m)
}
func (m *HashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HashResponse proto.InternalMessageInfo

func (m *HashResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HashResponse) GetHashedPassword() []byte {
	if m != nil {
		return m.HashedPassword
	}
	return nil
}

func (m *HashResponse) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

type ValidateRequest struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	HasshedPassword      []byte   `protobuf:"bytes,2,opt,name=hasshedPassword,proto3" json:"hasshedPassword,omitempty"`
	Salt                 []byte   `protobuf:"bytes,3,opt,name=salt,proto3" json:"salt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c0e1401011a1e2b, []int{2}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ValidateRequest) GetHasshedPassword() []byte {
	if m != nil {
		return m.HasshedPassword
	}
	return nil
}

func (m *ValidateRequest) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func init() {
	proto.RegisterType((*HashRequest)(nil), "ie.gmit.ps.HashRequest")
	proto.RegisterType((*HashResponse)(nil), "ie.gmit.ps.HashResponse")
	proto.RegisterType((*ValidateRequest)(nil), "ie.gmit.ps.ValidateRequest")
}

func init() { proto.RegisterFile("password_service.proto", fileDescriptor_3c0e1401011a1e2b) }

var fileDescriptor_3c0e1401011a1e2b = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x95, 0xa1, 0x54, 0xe5, 0xa8, 0x12, 0xc9, 0x43, 0x89, 0xcc, 0x82, 0x32, 0xa0, 0x4e, 0x1e,
	0x60, 0x62, 0xa4, 0x2c, 0xb0, 0x55, 0x41, 0x62, 0x45, 0x0e, 0x39, 0xd2, 0x88, 0x80, 0x8d, 0xcf,
	0xa1, 0xbf, 0x83, 0x7f, 0x8c, 0xc9, 0x07, 0x98, 0x50, 0x36, 0xdf, 0xbd, 0xe7, 0x77, 0xef, 0xde,
	0xc1, 0xc2, 0x28, 0xa2, 0xad, 0xb6, 0xc5, 0x03, 0xa1, 0x7d, 0xaf, 0x1e, 0x51, 0x1a, 0xab, 0x9d,
	0xe6, 0x50, 0xa1, 0x2c, 0x5f, 0x2a, 0x27, 0x0d, 0x89, 0x68, 0x6b, 0x95, 0x31, 0x68, 0xa9, 0xc3,
	0xd2, 0x2b, 0x38, 0xba, 0x51, 0xb4, 0xc9, 0xf0, 0xad, 0x41, 0x72, 0x7c, 0x01, 0xd3, 0xc6, 0x7f,
	0xbe, 0x2d, 0x12, 0x76, 0xca, 0x96, 0x07, 0x59, 0x5f, 0x71, 0x01, 0xb3, 0x41, 0x3c, 0xd9, 0xf3,
	0xc8, 0x61, 0xf6, 0x5d, 0xa7, 0x39, 0xcc, 0x3b, 0x09, 0x32, 0xfa, 0x95, 0xf0, 0x5f, 0x8d, 0x33,
	0x88, 0x36, 0x9e, 0x87, 0xc5, 0x3a, 0x54, 0x9a, 0x67, 0xa3, 0x2e, 0xe7, 0x30, 0x21, 0x55, 0xbb,
	0x64, 0xbf, 0x45, 0xdb, 0x77, 0xfa, 0x0c, 0xf1, 0xbd, 0xaa, 0xab, 0x42, 0x39, 0x1c, 0xac, 0x86,
	0x96, 0xd8, 0x6f, 0x4b, 0x7c, 0x09, 0xb1, 0x17, 0xdd, 0x31, 0x6b, 0xdc, 0xde, 0x35, 0xec, 0xfc,
	0x83, 0x41, 0x3c, 0x10, 0xee, 0xba, 0x24, 0xf9, 0x25, 0x4c, 0xbe, 0x96, 0xe4, 0xc7, 0xf2, 0x27,
	0x4c, 0x19, 0x24, 0x27, 0x92, 0xbf, 0x40, 0x9f, 0xc7, 0x35, 0xcc, 0x06, 0xef, 0xfc, 0x24, 0x64,
	0x8d, 0x36, 0x12, 0x42, 0x96, 0x5a, 0x97, 0x75, 0x7f, 0xb6, 0xbc, 0x79, 0x92, 0x2b, 0xad, 0x6b,
	0xcf, 0x6a, 0x70, 0x15, 0x41, 0x70, 0xc5, 0x35, 0xcb, 0xa7, 0x2d, 0xe7, 0xe2, 0x33, 0x00, 0x00,
	0xff, 0xff, 0xdc, 0x6b, 0x97, 0x3b, 0xf4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PasswordServiceClient is the client API for PasswordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PasswordServiceClient interface {
	Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
}

type passwordServiceClient struct {
	cc *grpc.ClientConn
}

func NewPasswordServiceClient(cc *grpc.ClientConn) PasswordServiceClient {
	return &passwordServiceClient{cc}
}

func (c *passwordServiceClient) Hash(ctx context.Context, in *HashRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	out := new(HashResponse)
	err := c.cc.Invoke(ctx, "/ie.gmit.ps.PasswordService/Hash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/ie.gmit.ps.PasswordService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasswordServiceServer is the server API for PasswordService service.
type PasswordServiceServer interface {
	Hash(context.Context, *HashRequest) (*HashResponse, error)
	Validate(context.Context, *ValidateRequest) (*wrappers.BoolValue, error)
}

// UnimplementedPasswordServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPasswordServiceServer struct {
}

func (*UnimplementedPasswordServiceServer) Hash(ctx context.Context, req *HashRequest) (*HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hash not implemented")
}
func (*UnimplementedPasswordServiceServer) Validate(ctx context.Context, req *ValidateRequest) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}

func RegisterPasswordServiceServer(s *grpc.Server, srv PasswordServiceServer) {
	s.RegisterService(&_PasswordService_serviceDesc, srv)
}

func _PasswordService_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordServiceServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ie.gmit.ps.PasswordService/Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordServiceServer).Hash(ctx, req.(*HashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PasswordService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ie.gmit.ps.PasswordService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PasswordService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ie.gmit.ps.PasswordService",
	HandlerType: (*PasswordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hash",
			Handler:    _PasswordService_Hash_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _PasswordService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "password_service.proto",
}
