// Code generated by protoc-gen-go. DO NOT EDIT.
// source: photo_shared.proto

package wcity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostType int32

const (
	PostType_CityTypePhoto  PostType = 0
	PostType_PlaceTypePhoto PostType = 1
)

var PostType_name = map[int32]string{
	0: "CityTypePhoto",
	1: "PlaceTypePhoto",
}

var PostType_value = map[string]int32{
	"CityTypePhoto":  0,
	"PlaceTypePhoto": 1,
}

func (x PostType) String() string {
	return proto.EnumName(PostType_name, int32(x))
}

func (PostType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dcbe3263bbb10a08, []int{0}
}

// Profile Photo
//
// Contains all data for display  a profile picture.
type ProfilePhoto struct {
	//Photo id, unique identifier of this image
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//User email is global unique identifier of the user
	UserEmail string `protobuf:"bytes,2,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	// url of the picture in the server,
	// used for display the picture
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	//Time of upload
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// true if is the fist image
	Selected             bool     `protobuf:"varint,5,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfilePhoto) Reset()         { *m = ProfilePhoto{} }
func (m *ProfilePhoto) String() string { return proto.CompactTextString(m) }
func (*ProfilePhoto) ProtoMessage()    {}
func (*ProfilePhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbe3263bbb10a08, []int{0}
}

func (m *ProfilePhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfilePhoto.Unmarshal(m, b)
}
func (m *ProfilePhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfilePhoto.Marshal(b, m, deterministic)
}
func (m *ProfilePhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfilePhoto.Merge(m, src)
}
func (m *ProfilePhoto) XXX_Size() int {
	return xxx_messageInfo_ProfilePhoto.Size(m)
}
func (m *ProfilePhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfilePhoto.DiscardUnknown(m)
}

var xxx_messageInfo_ProfilePhoto proto.InternalMessageInfo

func (m *ProfilePhoto) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProfilePhoto) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *ProfilePhoto) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ProfilePhoto) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *ProfilePhoto) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

// City Photo
//
// Contains all data for display  a city picture.
type CityPhoto struct {
	//Photo id, unique identifier of this image
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique identifier of the city, is the neo4jid
	CityId int32 `protobuf:"varint,2,opt,name=cityId,proto3" json:"cityId,omitempty"`
	// url of the picture in the server,
	// used for display the picture
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	//Time of upload
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// true if is the fist image
	Selected             bool     `protobuf:"varint,5,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityPhoto) Reset()         { *m = CityPhoto{} }
func (m *CityPhoto) String() string { return proto.CompactTextString(m) }
func (*CityPhoto) ProtoMessage()    {}
func (*CityPhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbe3263bbb10a08, []int{1}
}

func (m *CityPhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityPhoto.Unmarshal(m, b)
}
func (m *CityPhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityPhoto.Marshal(b, m, deterministic)
}
func (m *CityPhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityPhoto.Merge(m, src)
}
func (m *CityPhoto) XXX_Size() int {
	return xxx_messageInfo_CityPhoto.Size(m)
}
func (m *CityPhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_CityPhoto.DiscardUnknown(m)
}

var xxx_messageInfo_CityPhoto proto.InternalMessageInfo

func (m *CityPhoto) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CityPhoto) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *CityPhoto) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CityPhoto) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *CityPhoto) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

// Place Photo
//
// Contains all data for display  a place picture.
type PlacePhoto struct {
	//Photo id, unique identifier of this image
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Unique identifier of the place, is the neo4jid
	PlaceId int32 `protobuf:"varint,2,opt,name=placeId,proto3" json:"placeId,omitempty"`
	// url of the picture in the server,
	// used for display the picture
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	//Time of upload
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// true if is the fist image
	Selected bool `protobuf:"varint,5,opt,name=selected,proto3" json:"selected,omitempty"`
	//City of the place
	PlaceCityId          int32    `protobuf:"varint,6,opt,name=placeCityId,proto3" json:"placeCityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlacePhoto) Reset()         { *m = PlacePhoto{} }
func (m *PlacePhoto) String() string { return proto.CompactTextString(m) }
func (*PlacePhoto) ProtoMessage()    {}
func (*PlacePhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbe3263bbb10a08, []int{2}
}

func (m *PlacePhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacePhoto.Unmarshal(m, b)
}
func (m *PlacePhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacePhoto.Marshal(b, m, deterministic)
}
func (m *PlacePhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacePhoto.Merge(m, src)
}
func (m *PlacePhoto) XXX_Size() int {
	return xxx_messageInfo_PlacePhoto.Size(m)
}
func (m *PlacePhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacePhoto.DiscardUnknown(m)
}

var xxx_messageInfo_PlacePhoto proto.InternalMessageInfo

func (m *PlacePhoto) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PlacePhoto) GetPlaceId() int32 {
	if m != nil {
		return m.PlaceId
	}
	return 0
}

func (m *PlacePhoto) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PlacePhoto) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *PlacePhoto) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

func (m *PlacePhoto) GetPlaceCityId() int32 {
	if m != nil {
		return m.PlaceCityId
	}
	return 0
}

// Post Photo
//
// Contains all data for display  a post picture.
type PostPhoto struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId               string   `protobuf:"bytes,2,opt,name=postId,proto3" json:"postId,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Selected             bool     `protobuf:"varint,5,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostPhoto) Reset()         { *m = PostPhoto{} }
func (m *PostPhoto) String() string { return proto.CompactTextString(m) }
func (*PostPhoto) ProtoMessage()    {}
func (*PostPhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbe3263bbb10a08, []int{3}
}

func (m *PostPhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostPhoto.Unmarshal(m, b)
}
func (m *PostPhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostPhoto.Marshal(b, m, deterministic)
}
func (m *PostPhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostPhoto.Merge(m, src)
}
func (m *PostPhoto) XXX_Size() int {
	return xxx_messageInfo_PostPhoto.Size(m)
}
func (m *PostPhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_PostPhoto.DiscardUnknown(m)
}

var xxx_messageInfo_PostPhoto proto.InternalMessageInfo

func (m *PostPhoto) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PostPhoto) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *PostPhoto) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PostPhoto) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *PostPhoto) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

type CitysPhoto struct {
	CityId               int32        `protobuf:"varint,1,opt,name=cityId,proto3" json:"cityId,omitempty"`
	CitysPhotos          []*CityPhoto `protobuf:"bytes,2,rep,name=citysPhotos,proto3" json:"citysPhotos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CitysPhoto) Reset()         { *m = CitysPhoto{} }
func (m *CitysPhoto) String() string { return proto.CompactTextString(m) }
func (*CitysPhoto) ProtoMessage()    {}
func (*CitysPhoto) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbe3263bbb10a08, []int{4}
}

func (m *CitysPhoto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CitysPhoto.Unmarshal(m, b)
}
func (m *CitysPhoto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CitysPhoto.Marshal(b, m, deterministic)
}
func (m *CitysPhoto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CitysPhoto.Merge(m, src)
}
func (m *CitysPhoto) XXX_Size() int {
	return xxx_messageInfo_CitysPhoto.Size(m)
}
func (m *CitysPhoto) XXX_DiscardUnknown() {
	xxx_messageInfo_CitysPhoto.DiscardUnknown(m)
}

var xxx_messageInfo_CitysPhoto proto.InternalMessageInfo

func (m *CitysPhoto) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *CitysPhoto) GetCitysPhotos() []*CityPhoto {
	if m != nil {
		return m.CitysPhotos
	}
	return nil
}

type PlacesCityPhotos struct {
	CityId               int32         `protobuf:"varint,1,opt,name=cityId,proto3" json:"cityId,omitempty"`
	PlaceId              int32         `protobuf:"varint,2,opt,name=placeId,proto3" json:"placeId,omitempty"`
	PlacePhotos          []*PlacePhoto `protobuf:"bytes,3,rep,name=placePhotos,proto3" json:"placePhotos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlacesCityPhotos) Reset()         { *m = PlacesCityPhotos{} }
func (m *PlacesCityPhotos) String() string { return proto.CompactTextString(m) }
func (*PlacesCityPhotos) ProtoMessage()    {}
func (*PlacesCityPhotos) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcbe3263bbb10a08, []int{5}
}

func (m *PlacesCityPhotos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacesCityPhotos.Unmarshal(m, b)
}
func (m *PlacesCityPhotos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacesCityPhotos.Marshal(b, m, deterministic)
}
func (m *PlacesCityPhotos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacesCityPhotos.Merge(m, src)
}
func (m *PlacesCityPhotos) XXX_Size() int {
	return xxx_messageInfo_PlacesCityPhotos.Size(m)
}
func (m *PlacesCityPhotos) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacesCityPhotos.DiscardUnknown(m)
}

var xxx_messageInfo_PlacesCityPhotos proto.InternalMessageInfo

func (m *PlacesCityPhotos) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *PlacesCityPhotos) GetPlaceId() int32 {
	if m != nil {
		return m.PlaceId
	}
	return 0
}

func (m *PlacesCityPhotos) GetPlacePhotos() []*PlacePhoto {
	if m != nil {
		return m.PlacePhotos
	}
	return nil
}

func init() {
	proto.RegisterEnum("wcity.PostType", PostType_name, PostType_value)
	proto.RegisterType((*ProfilePhoto)(nil), "wcity.ProfilePhoto")
	proto.RegisterType((*CityPhoto)(nil), "wcity.CityPhoto")
	proto.RegisterType((*PlacePhoto)(nil), "wcity.PlacePhoto")
	proto.RegisterType((*PostPhoto)(nil), "wcity.PostPhoto")
	proto.RegisterType((*CitysPhoto)(nil), "wcity.CitysPhoto")
	proto.RegisterType((*PlacesCityPhotos)(nil), "wcity.PlacesCityPhotos")
}

func init() { proto.RegisterFile("photo_shared.proto", fileDescriptor_dcbe3263bbb10a08) }

var fileDescriptor_dcbe3263bbb10a08 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x93, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x71, 0x43, 0x4a, 0x73, 0x85, 0x2a, 0xf5, 0x80, 0x02, 0x62, 0xa8, 0x3a, 0x55, 0x0c,
	0x91, 0x68, 0xc5, 0x0b, 0xb4, 0x62, 0x60, 0xb3, 0x0c, 0x03, 0x1b, 0x0a, 0x89, 0xa1, 0x91, 0x52,
	0xc5, 0x8a, 0x53, 0xa1, 0x4e, 0xac, 0x3c, 0x07, 0xe2, 0x41, 0xb1, 0xaf, 0xc6, 0x29, 0x12, 0xd9,
	0xb2, 0xf9, 0xfe, 0xf4, 0xee, 0xd7, 0xef, 0xcb, 0x01, 0x95, 0xeb, 0xb2, 0x2e, 0x9f, 0xd5, 0x3a,
	0xa9, 0x44, 0x16, 0xcb, 0x4a, 0x07, 0xd4, 0x7f, 0x4f, 0xf3, 0x7a, 0x37, 0xfd, 0x24, 0x70, 0xca,
	0xaa, 0xf2, 0x35, 0x2f, 0x04, 0x33, 0x4d, 0x74, 0x04, 0xbd, 0x3c, 0x8b, 0xc8, 0x84, 0xcc, 0x7c,
	0xae, 0x5f, 0xf4, 0x0a, 0x82, 0xad, 0x12, 0xd5, 0xdd, 0x26, 0xc9, 0x8b, 0xa8, 0xa7, 0xd3, 0x01,
	0x6f, 0x12, 0x34, 0x04, 0x6f, 0x5b, 0x15, 0x91, 0x87, 0x79, 0xf3, 0x34, 0xfd, 0x75, 0xbe, 0x11,
	0xaa, 0x4e, 0x36, 0x32, 0x3a, 0xde, 0xf7, 0xbb, 0x04, 0xbd, 0x84, 0x81, 0x12, 0x85, 0x48, 0x6b,
	0x91, 0x45, 0xbe, 0x2e, 0x0e, 0xb8, 0x8b, 0xa7, 0x1f, 0x10, 0xac, 0x34, 0xd2, 0xff, 0x18, 0xe7,
	0xd0, 0x37, 0xbc, 0xf7, 0x19, 0x32, 0xf8, 0xdc, 0x46, 0x9d, 0x02, 0x7c, 0x13, 0x00, 0x56, 0x24,
	0x69, 0x8b, 0x12, 0x11, 0x9c, 0x48, 0x53, 0x75, 0x0c, 0xbf, 0x61, 0x97, 0x10, 0x74, 0x02, 0x43,
	0x1c, 0xbb, 0xda, 0xff, 0xdb, 0x3e, 0x6e, 0x3a, 0x4c, 0x19, 0x9d, 0x58, 0xa9, 0xea, 0x56, 0x9d,
	0xa4, 0x2e, 0x5a, 0xc6, 0x80, 0xdb, 0xa8, 0x53, 0x9d, 0x9e, 0x00, 0x0c, 0x8a, 0xda, 0x13, 0x34,
	0xce, 0x90, 0x3f, 0xce, 0xcc, 0x61, 0x98, 0xba, 0x2e, 0xa5, 0x71, 0xbc, 0xd9, 0x70, 0x1e, 0xc6,
	0xf8, 0xd9, 0xc5, 0xce, 0x68, 0x7e, 0xd8, 0x34, 0xdd, 0x41, 0x88, 0x06, 0x28, 0x57, 0x57, 0xad,
	0xf3, 0xdb, 0xed, 0x58, 0x58, 0x09, 0xed, 0x66, 0x0f, 0x37, 0x8f, 0xed, 0xe6, 0xc6, 0x60, 0x7e,
	0xd8, 0x75, 0x7d, 0x03, 0x03, 0xa3, 0xea, 0xe3, 0x4e, 0x0a, 0x3a, 0x86, 0x33, 0x03, 0x60, 0xde,
	0x58, 0x0d, 0x8f, 0x28, 0x85, 0x11, 0xfe, 0xb2, 0xc9, 0x91, 0xe5, 0x2d, 0x5c, 0xe4, 0x65, 0xfc,
	0x56, 0xc9, 0xd4, 0xce, 0xc6, 0x33, 0x7b, 0xc0, 0x2b, 0x5b, 0x86, 0xac, 0x09, 0x98, 0xb9, 0x38,
	0x46, 0xbe, 0x7a, 0x1e, 0x67, 0xab, 0x97, 0x3e, 0x1e, 0xe0, 0xe2, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x22, 0xfe, 0xc1, 0x94, 0x96, 0x03, 0x00, 0x00,
}
