// Code generated by protoc-gen-go. DO NOT EDIT.
// source: photosdba.proto

package wcity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddProfilePhotoDBARequest struct {
	UserEmail            string   `protobuf:"bytes,1,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Selected             bool     `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProfilePhotoDBARequest) Reset()         { *m = AddProfilePhotoDBARequest{} }
func (m *AddProfilePhotoDBARequest) String() string { return proto.CompactTextString(m) }
func (*AddProfilePhotoDBARequest) ProtoMessage()    {}
func (*AddProfilePhotoDBARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{0}
}

func (m *AddProfilePhotoDBARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProfilePhotoDBARequest.Unmarshal(m, b)
}
func (m *AddProfilePhotoDBARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProfilePhotoDBARequest.Marshal(b, m, deterministic)
}
func (m *AddProfilePhotoDBARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProfilePhotoDBARequest.Merge(m, src)
}
func (m *AddProfilePhotoDBARequest) XXX_Size() int {
	return xxx_messageInfo_AddProfilePhotoDBARequest.Size(m)
}
func (m *AddProfilePhotoDBARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProfilePhotoDBARequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddProfilePhotoDBARequest proto.InternalMessageInfo

func (m *AddProfilePhotoDBARequest) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *AddProfilePhotoDBARequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AddProfilePhotoDBARequest) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

type AddProfilePhotoDBAResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	TimeStamp            string   `protobuf:"bytes,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProfilePhotoDBAResponse) Reset()         { *m = AddProfilePhotoDBAResponse{} }
func (m *AddProfilePhotoDBAResponse) String() string { return proto.CompactTextString(m) }
func (*AddProfilePhotoDBAResponse) ProtoMessage()    {}
func (*AddProfilePhotoDBAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{1}
}

func (m *AddProfilePhotoDBAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProfilePhotoDBAResponse.Unmarshal(m, b)
}
func (m *AddProfilePhotoDBAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProfilePhotoDBAResponse.Marshal(b, m, deterministic)
}
func (m *AddProfilePhotoDBAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProfilePhotoDBAResponse.Merge(m, src)
}
func (m *AddProfilePhotoDBAResponse) XXX_Size() int {
	return xxx_messageInfo_AddProfilePhotoDBAResponse.Size(m)
}
func (m *AddProfilePhotoDBAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProfilePhotoDBAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddProfilePhotoDBAResponse proto.InternalMessageInfo

func (m *AddProfilePhotoDBAResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddProfilePhotoDBAResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddProfilePhotoDBAResponse) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

type AddCityPhotoDBARequest struct {
	CityId               int32    `protobuf:"varint,1,opt,name=cityId,proto3" json:"cityId,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Selected             bool     `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCityPhotoDBARequest) Reset()         { *m = AddCityPhotoDBARequest{} }
func (m *AddCityPhotoDBARequest) String() string { return proto.CompactTextString(m) }
func (*AddCityPhotoDBARequest) ProtoMessage()    {}
func (*AddCityPhotoDBARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{2}
}

func (m *AddCityPhotoDBARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCityPhotoDBARequest.Unmarshal(m, b)
}
func (m *AddCityPhotoDBARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCityPhotoDBARequest.Marshal(b, m, deterministic)
}
func (m *AddCityPhotoDBARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCityPhotoDBARequest.Merge(m, src)
}
func (m *AddCityPhotoDBARequest) XXX_Size() int {
	return xxx_messageInfo_AddCityPhotoDBARequest.Size(m)
}
func (m *AddCityPhotoDBARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCityPhotoDBARequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCityPhotoDBARequest proto.InternalMessageInfo

func (m *AddCityPhotoDBARequest) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

func (m *AddCityPhotoDBARequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AddCityPhotoDBARequest) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

type AddCityPhotoDBAResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	TimeStamp            string   `protobuf:"bytes,3,opt,name=TimeStamp,json=timeStamp,proto3" json:"TimeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCityPhotoDBAResponse) Reset()         { *m = AddCityPhotoDBAResponse{} }
func (m *AddCityPhotoDBAResponse) String() string { return proto.CompactTextString(m) }
func (*AddCityPhotoDBAResponse) ProtoMessage()    {}
func (*AddCityPhotoDBAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{3}
}

func (m *AddCityPhotoDBAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCityPhotoDBAResponse.Unmarshal(m, b)
}
func (m *AddCityPhotoDBAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCityPhotoDBAResponse.Marshal(b, m, deterministic)
}
func (m *AddCityPhotoDBAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCityPhotoDBAResponse.Merge(m, src)
}
func (m *AddCityPhotoDBAResponse) XXX_Size() int {
	return xxx_messageInfo_AddCityPhotoDBAResponse.Size(m)
}
func (m *AddCityPhotoDBAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCityPhotoDBAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddCityPhotoDBAResponse proto.InternalMessageInfo

func (m *AddCityPhotoDBAResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddCityPhotoDBAResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddCityPhotoDBAResponse) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

type AddPlacePhotoDBARequest struct {
	PlaceId              int32    `protobuf:"varint,1,opt,name=placeId,proto3" json:"placeId,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Selected             bool     `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	PlaceCityId          int32    `protobuf:"varint,4,opt,name=placeCityId,proto3" json:"placeCityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPlacePhotoDBARequest) Reset()         { *m = AddPlacePhotoDBARequest{} }
func (m *AddPlacePhotoDBARequest) String() string { return proto.CompactTextString(m) }
func (*AddPlacePhotoDBARequest) ProtoMessage()    {}
func (*AddPlacePhotoDBARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{4}
}

func (m *AddPlacePhotoDBARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlacePhotoDBARequest.Unmarshal(m, b)
}
func (m *AddPlacePhotoDBARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlacePhotoDBARequest.Marshal(b, m, deterministic)
}
func (m *AddPlacePhotoDBARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlacePhotoDBARequest.Merge(m, src)
}
func (m *AddPlacePhotoDBARequest) XXX_Size() int {
	return xxx_messageInfo_AddPlacePhotoDBARequest.Size(m)
}
func (m *AddPlacePhotoDBARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlacePhotoDBARequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlacePhotoDBARequest proto.InternalMessageInfo

func (m *AddPlacePhotoDBARequest) GetPlaceId() int32 {
	if m != nil {
		return m.PlaceId
	}
	return 0
}

func (m *AddPlacePhotoDBARequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AddPlacePhotoDBARequest) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

func (m *AddPlacePhotoDBARequest) GetPlaceCityId() int32 {
	if m != nil {
		return m.PlaceCityId
	}
	return 0
}

type AddPlacePhotoDBAResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Sd                   int32    `protobuf:"varint,2,opt,name=sd,proto3" json:"sd,omitempty"`
	TimeStamp            string   `protobuf:"bytes,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPlacePhotoDBAResponse) Reset()         { *m = AddPlacePhotoDBAResponse{} }
func (m *AddPlacePhotoDBAResponse) String() string { return proto.CompactTextString(m) }
func (*AddPlacePhotoDBAResponse) ProtoMessage()    {}
func (*AddPlacePhotoDBAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{5}
}

func (m *AddPlacePhotoDBAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlacePhotoDBAResponse.Unmarshal(m, b)
}
func (m *AddPlacePhotoDBAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlacePhotoDBAResponse.Marshal(b, m, deterministic)
}
func (m *AddPlacePhotoDBAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlacePhotoDBAResponse.Merge(m, src)
}
func (m *AddPlacePhotoDBAResponse) XXX_Size() int {
	return xxx_messageInfo_AddPlacePhotoDBAResponse.Size(m)
}
func (m *AddPlacePhotoDBAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlacePhotoDBAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlacePhotoDBAResponse proto.InternalMessageInfo

func (m *AddPlacePhotoDBAResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddPlacePhotoDBAResponse) GetSd() int32 {
	if m != nil {
		return m.Sd
	}
	return 0
}

func (m *AddPlacePhotoDBAResponse) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

type AddPostPhotoDBARequest struct {
	PostId               string   `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Selected             bool     `protobuf:"varint,3,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostPhotoDBARequest) Reset()         { *m = AddPostPhotoDBARequest{} }
func (m *AddPostPhotoDBARequest) String() string { return proto.CompactTextString(m) }
func (*AddPostPhotoDBARequest) ProtoMessage()    {}
func (*AddPostPhotoDBARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{6}
}

func (m *AddPostPhotoDBARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostPhotoDBARequest.Unmarshal(m, b)
}
func (m *AddPostPhotoDBARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostPhotoDBARequest.Marshal(b, m, deterministic)
}
func (m *AddPostPhotoDBARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostPhotoDBARequest.Merge(m, src)
}
func (m *AddPostPhotoDBARequest) XXX_Size() int {
	return xxx_messageInfo_AddPostPhotoDBARequest.Size(m)
}
func (m *AddPostPhotoDBARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostPhotoDBARequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostPhotoDBARequest proto.InternalMessageInfo

func (m *AddPostPhotoDBARequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *AddPostPhotoDBARequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AddPostPhotoDBARequest) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

type AddPostPhotoDBAResponse struct {
	Sucess               bool     `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	TimeStamp            string   `protobuf:"bytes,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPostPhotoDBAResponse) Reset()         { *m = AddPostPhotoDBAResponse{} }
func (m *AddPostPhotoDBAResponse) String() string { return proto.CompactTextString(m) }
func (*AddPostPhotoDBAResponse) ProtoMessage()    {}
func (*AddPostPhotoDBAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{7}
}

func (m *AddPostPhotoDBAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPostPhotoDBAResponse.Unmarshal(m, b)
}
func (m *AddPostPhotoDBAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPostPhotoDBAResponse.Marshal(b, m, deterministic)
}
func (m *AddPostPhotoDBAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPostPhotoDBAResponse.Merge(m, src)
}
func (m *AddPostPhotoDBAResponse) XXX_Size() int {
	return xxx_messageInfo_AddPostPhotoDBAResponse.Size(m)
}
func (m *AddPostPhotoDBAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPostPhotoDBAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPostPhotoDBAResponse proto.InternalMessageInfo

func (m *AddPostPhotoDBAResponse) GetSucess() bool {
	if m != nil {
		return m.Sucess
	}
	return false
}

func (m *AddPostPhotoDBAResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddPostPhotoDBAResponse) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

type GetProfilePhotosDBARequest struct {
	UserEmail            string   `protobuf:"bytes,1,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfilePhotosDBARequest) Reset()         { *m = GetProfilePhotosDBARequest{} }
func (m *GetProfilePhotosDBARequest) String() string { return proto.CompactTextString(m) }
func (*GetProfilePhotosDBARequest) ProtoMessage()    {}
func (*GetProfilePhotosDBARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{8}
}

func (m *GetProfilePhotosDBARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfilePhotosDBARequest.Unmarshal(m, b)
}
func (m *GetProfilePhotosDBARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfilePhotosDBARequest.Marshal(b, m, deterministic)
}
func (m *GetProfilePhotosDBARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfilePhotosDBARequest.Merge(m, src)
}
func (m *GetProfilePhotosDBARequest) XXX_Size() int {
	return xxx_messageInfo_GetProfilePhotosDBARequest.Size(m)
}
func (m *GetProfilePhotosDBARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfilePhotosDBARequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfilePhotosDBARequest proto.InternalMessageInfo

func (m *GetProfilePhotosDBARequest) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

type GetProfilePhotosDBAResponse struct {
	Sucess               bool            `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	Photos               []*ProfilePhoto `protobuf:"bytes,2,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetProfilePhotosDBAResponse) Reset()         { *m = GetProfilePhotosDBAResponse{} }
func (m *GetProfilePhotosDBAResponse) String() string { return proto.CompactTextString(m) }
func (*GetProfilePhotosDBAResponse) ProtoMessage()    {}
func (*GetProfilePhotosDBAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{9}
}

func (m *GetProfilePhotosDBAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfilePhotosDBAResponse.Unmarshal(m, b)
}
func (m *GetProfilePhotosDBAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfilePhotosDBAResponse.Marshal(b, m, deterministic)
}
func (m *GetProfilePhotosDBAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfilePhotosDBAResponse.Merge(m, src)
}
func (m *GetProfilePhotosDBAResponse) XXX_Size() int {
	return xxx_messageInfo_GetProfilePhotosDBAResponse.Size(m)
}
func (m *GetProfilePhotosDBAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfilePhotosDBAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfilePhotosDBAResponse proto.InternalMessageInfo

func (m *GetProfilePhotosDBAResponse) GetSucess() bool {
	if m != nil {
		return m.Sucess
	}
	return false
}

func (m *GetProfilePhotosDBAResponse) GetPhotos() []*ProfilePhoto {
	if m != nil {
		return m.Photos
	}
	return nil
}

type GetCityPhotosDBARequest struct {
	CityId               int32    `protobuf:"varint,1,opt,name=cityId,proto3" json:"cityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCityPhotosDBARequest) Reset()         { *m = GetCityPhotosDBARequest{} }
func (m *GetCityPhotosDBARequest) String() string { return proto.CompactTextString(m) }
func (*GetCityPhotosDBARequest) ProtoMessage()    {}
func (*GetCityPhotosDBARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{10}
}

func (m *GetCityPhotosDBARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCityPhotosDBARequest.Unmarshal(m, b)
}
func (m *GetCityPhotosDBARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCityPhotosDBARequest.Marshal(b, m, deterministic)
}
func (m *GetCityPhotosDBARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCityPhotosDBARequest.Merge(m, src)
}
func (m *GetCityPhotosDBARequest) XXX_Size() int {
	return xxx_messageInfo_GetCityPhotosDBARequest.Size(m)
}
func (m *GetCityPhotosDBARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCityPhotosDBARequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCityPhotosDBARequest proto.InternalMessageInfo

func (m *GetCityPhotosDBARequest) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type GetCityPhotosDBAResponse struct {
	Sucess               bool         `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	Photos               []*CityPhoto `protobuf:"bytes,2,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetCityPhotosDBAResponse) Reset()         { *m = GetCityPhotosDBAResponse{} }
func (m *GetCityPhotosDBAResponse) String() string { return proto.CompactTextString(m) }
func (*GetCityPhotosDBAResponse) ProtoMessage()    {}
func (*GetCityPhotosDBAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{11}
}

func (m *GetCityPhotosDBAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCityPhotosDBAResponse.Unmarshal(m, b)
}
func (m *GetCityPhotosDBAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCityPhotosDBAResponse.Marshal(b, m, deterministic)
}
func (m *GetCityPhotosDBAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCityPhotosDBAResponse.Merge(m, src)
}
func (m *GetCityPhotosDBAResponse) XXX_Size() int {
	return xxx_messageInfo_GetCityPhotosDBAResponse.Size(m)
}
func (m *GetCityPhotosDBAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCityPhotosDBAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCityPhotosDBAResponse proto.InternalMessageInfo

func (m *GetCityPhotosDBAResponse) GetSucess() bool {
	if m != nil {
		return m.Sucess
	}
	return false
}

func (m *GetCityPhotosDBAResponse) GetPhotos() []*CityPhoto {
	if m != nil {
		return m.Photos
	}
	return nil
}

type GetPlacePhotosDBARequest struct {
	PlaceId              int32    `protobuf:"varint,1,opt,name=placeId,proto3" json:"placeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlacePhotosDBARequest) Reset()         { *m = GetPlacePhotosDBARequest{} }
func (m *GetPlacePhotosDBARequest) String() string { return proto.CompactTextString(m) }
func (*GetPlacePhotosDBARequest) ProtoMessage()    {}
func (*GetPlacePhotosDBARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{12}
}

func (m *GetPlacePhotosDBARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlacePhotosDBARequest.Unmarshal(m, b)
}
func (m *GetPlacePhotosDBARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlacePhotosDBARequest.Marshal(b, m, deterministic)
}
func (m *GetPlacePhotosDBARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlacePhotosDBARequest.Merge(m, src)
}
func (m *GetPlacePhotosDBARequest) XXX_Size() int {
	return xxx_messageInfo_GetPlacePhotosDBARequest.Size(m)
}
func (m *GetPlacePhotosDBARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlacePhotosDBARequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlacePhotosDBARequest proto.InternalMessageInfo

func (m *GetPlacePhotosDBARequest) GetPlaceId() int32 {
	if m != nil {
		return m.PlaceId
	}
	return 0
}

type GetPlacePhotosDBAResponse struct {
	Sucess               bool          `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	Photos               []*PlacePhoto `protobuf:"bytes,2,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPlacePhotosDBAResponse) Reset()         { *m = GetPlacePhotosDBAResponse{} }
func (m *GetPlacePhotosDBAResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlacePhotosDBAResponse) ProtoMessage()    {}
func (*GetPlacePhotosDBAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{13}
}

func (m *GetPlacePhotosDBAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlacePhotosDBAResponse.Unmarshal(m, b)
}
func (m *GetPlacePhotosDBAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlacePhotosDBAResponse.Marshal(b, m, deterministic)
}
func (m *GetPlacePhotosDBAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlacePhotosDBAResponse.Merge(m, src)
}
func (m *GetPlacePhotosDBAResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlacePhotosDBAResponse.Size(m)
}
func (m *GetPlacePhotosDBAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlacePhotosDBAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlacePhotosDBAResponse proto.InternalMessageInfo

func (m *GetPlacePhotosDBAResponse) GetSucess() bool {
	if m != nil {
		return m.Sucess
	}
	return false
}

func (m *GetPlacePhotosDBAResponse) GetPhotos() []*PlacePhoto {
	if m != nil {
		return m.Photos
	}
	return nil
}

type GetPostPhotosDBARequest struct {
	PlaceId              string   `protobuf:"bytes,1,opt,name=placeId,proto3" json:"placeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostPhotosDBARequest) Reset()         { *m = GetPostPhotosDBARequest{} }
func (m *GetPostPhotosDBARequest) String() string { return proto.CompactTextString(m) }
func (*GetPostPhotosDBARequest) ProtoMessage()    {}
func (*GetPostPhotosDBARequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{14}
}

func (m *GetPostPhotosDBARequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostPhotosDBARequest.Unmarshal(m, b)
}
func (m *GetPostPhotosDBARequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostPhotosDBARequest.Marshal(b, m, deterministic)
}
func (m *GetPostPhotosDBARequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostPhotosDBARequest.Merge(m, src)
}
func (m *GetPostPhotosDBARequest) XXX_Size() int {
	return xxx_messageInfo_GetPostPhotosDBARequest.Size(m)
}
func (m *GetPostPhotosDBARequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostPhotosDBARequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostPhotosDBARequest proto.InternalMessageInfo

func (m *GetPostPhotosDBARequest) GetPlaceId() string {
	if m != nil {
		return m.PlaceId
	}
	return ""
}

type GetPostPhotosDBAResponse struct {
	Sucess               bool         `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	Photos               []*PostPhoto `protobuf:"bytes,2,rep,name=photos,proto3" json:"photos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPostPhotosDBAResponse) Reset()         { *m = GetPostPhotosDBAResponse{} }
func (m *GetPostPhotosDBAResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostPhotosDBAResponse) ProtoMessage()    {}
func (*GetPostPhotosDBAResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{15}
}

func (m *GetPostPhotosDBAResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostPhotosDBAResponse.Unmarshal(m, b)
}
func (m *GetPostPhotosDBAResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostPhotosDBAResponse.Marshal(b, m, deterministic)
}
func (m *GetPostPhotosDBAResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostPhotosDBAResponse.Merge(m, src)
}
func (m *GetPostPhotosDBAResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostPhotosDBAResponse.Size(m)
}
func (m *GetPostPhotosDBAResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostPhotosDBAResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostPhotosDBAResponse proto.InternalMessageInfo

func (m *GetPostPhotosDBAResponse) GetSucess() bool {
	if m != nil {
		return m.Sucess
	}
	return false
}

func (m *GetPostPhotosDBAResponse) GetPhotos() []*PostPhoto {
	if m != nil {
		return m.Photos
	}
	return nil
}

type GetCitysPhotoRequest struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCitysPhotoRequest) Reset()         { *m = GetCitysPhotoRequest{} }
func (m *GetCitysPhotoRequest) String() string { return proto.CompactTextString(m) }
func (*GetCitysPhotoRequest) ProtoMessage()    {}
func (*GetCitysPhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{16}
}

func (m *GetCitysPhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCitysPhotoRequest.Unmarshal(m, b)
}
func (m *GetCitysPhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCitysPhotoRequest.Marshal(b, m, deterministic)
}
func (m *GetCitysPhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCitysPhotoRequest.Merge(m, src)
}
func (m *GetCitysPhotoRequest) XXX_Size() int {
	return xxx_messageInfo_GetCitysPhotoRequest.Size(m)
}
func (m *GetCitysPhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCitysPhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCitysPhotoRequest proto.InternalMessageInfo

func (m *GetCitysPhotoRequest) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type GetCitysPhotoResponse struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CityPhotos           []*CitysPhoto `protobuf:"bytes,2,rep,name=cityPhotos,proto3" json:"cityPhotos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetCitysPhotoResponse) Reset()         { *m = GetCitysPhotoResponse{} }
func (m *GetCitysPhotoResponse) String() string { return proto.CompactTextString(m) }
func (*GetCitysPhotoResponse) ProtoMessage()    {}
func (*GetCitysPhotoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{17}
}

func (m *GetCitysPhotoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCitysPhotoResponse.Unmarshal(m, b)
}
func (m *GetCitysPhotoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCitysPhotoResponse.Marshal(b, m, deterministic)
}
func (m *GetCitysPhotoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCitysPhotoResponse.Merge(m, src)
}
func (m *GetCitysPhotoResponse) XXX_Size() int {
	return xxx_messageInfo_GetCitysPhotoResponse.Size(m)
}
func (m *GetCitysPhotoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCitysPhotoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCitysPhotoResponse proto.InternalMessageInfo

func (m *GetCitysPhotoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetCitysPhotoResponse) GetCityPhotos() []*CitysPhoto {
	if m != nil {
		return m.CityPhotos
	}
	return nil
}

type GetPlacesPhotosPerCityRequest struct {
	CityPlaceId          int32    `protobuf:"varint,1,opt,name=cityPlaceId,proto3" json:"cityPlaceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlacesPhotosPerCityRequest) Reset()         { *m = GetPlacesPhotosPerCityRequest{} }
func (m *GetPlacesPhotosPerCityRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlacesPhotosPerCityRequest) ProtoMessage()    {}
func (*GetPlacesPhotosPerCityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{18}
}

func (m *GetPlacesPhotosPerCityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlacesPhotosPerCityRequest.Unmarshal(m, b)
}
func (m *GetPlacesPhotosPerCityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlacesPhotosPerCityRequest.Marshal(b, m, deterministic)
}
func (m *GetPlacesPhotosPerCityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlacesPhotosPerCityRequest.Merge(m, src)
}
func (m *GetPlacesPhotosPerCityRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlacesPhotosPerCityRequest.Size(m)
}
func (m *GetPlacesPhotosPerCityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlacesPhotosPerCityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlacesPhotosPerCityRequest proto.InternalMessageInfo

func (m *GetPlacesPhotosPerCityRequest) GetCityPlaceId() int32 {
	if m != nil {
		return m.CityPlaceId
	}
	return 0
}

type GetPlacesPhotosPerCityResponse struct {
	Success              bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PlacePhotos          []*PlacesCityPhotos `protobuf:"bytes,2,rep,name=placePhotos,proto3" json:"placePhotos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetPlacesPhotosPerCityResponse) Reset()         { *m = GetPlacesPhotosPerCityResponse{} }
func (m *GetPlacesPhotosPerCityResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlacesPhotosPerCityResponse) ProtoMessage()    {}
func (*GetPlacesPhotosPerCityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{19}
}

func (m *GetPlacesPhotosPerCityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlacesPhotosPerCityResponse.Unmarshal(m, b)
}
func (m *GetPlacesPhotosPerCityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlacesPhotosPerCityResponse.Marshal(b, m, deterministic)
}
func (m *GetPlacesPhotosPerCityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlacesPhotosPerCityResponse.Merge(m, src)
}
func (m *GetPlacesPhotosPerCityResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlacesPhotosPerCityResponse.Size(m)
}
func (m *GetPlacesPhotosPerCityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlacesPhotosPerCityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlacesPhotosPerCityResponse proto.InternalMessageInfo

func (m *GetPlacesPhotosPerCityResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetPlacesPhotosPerCityResponse) GetPlacePhotos() []*PlacesCityPhotos {
	if m != nil {
		return m.PlacePhotos
	}
	return nil
}

type GetPostsPhotosPerParentRequest struct {
	Type                 PostType `protobuf:"varint,1,opt,name=type,proto3,enum=wcity.PostType" json:"type,omitempty"`
	ParentId             int32    `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsPhotosPerParentRequest) Reset()         { *m = GetPostsPhotosPerParentRequest{} }
func (m *GetPostsPhotosPerParentRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostsPhotosPerParentRequest) ProtoMessage()    {}
func (*GetPostsPhotosPerParentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{20}
}

func (m *GetPostsPhotosPerParentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsPhotosPerParentRequest.Unmarshal(m, b)
}
func (m *GetPostsPhotosPerParentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsPhotosPerParentRequest.Marshal(b, m, deterministic)
}
func (m *GetPostsPhotosPerParentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsPhotosPerParentRequest.Merge(m, src)
}
func (m *GetPostsPhotosPerParentRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostsPhotosPerParentRequest.Size(m)
}
func (m *GetPostsPhotosPerParentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsPhotosPerParentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsPhotosPerParentRequest proto.InternalMessageInfo

func (m *GetPostsPhotosPerParentRequest) GetType() PostType {
	if m != nil {
		return m.Type
	}
	return PostType_City
}

func (m *GetPostsPhotosPerParentRequest) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type GetPostsPhotosPerParentResponse struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PlacesPhoto          []*PlacePhoto `protobuf:"bytes,2,rep,name=placesPhoto,proto3" json:"placesPhoto,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPostsPhotosPerParentResponse) Reset()         { *m = GetPostsPhotosPerParentResponse{} }
func (m *GetPostsPhotosPerParentResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostsPhotosPerParentResponse) ProtoMessage()    {}
func (*GetPostsPhotosPerParentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d9ff4e76b59f186, []int{21}
}

func (m *GetPostsPhotosPerParentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsPhotosPerParentResponse.Unmarshal(m, b)
}
func (m *GetPostsPhotosPerParentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsPhotosPerParentResponse.Marshal(b, m, deterministic)
}
func (m *GetPostsPhotosPerParentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsPhotosPerParentResponse.Merge(m, src)
}
func (m *GetPostsPhotosPerParentResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostsPhotosPerParentResponse.Size(m)
}
func (m *GetPostsPhotosPerParentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsPhotosPerParentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsPhotosPerParentResponse proto.InternalMessageInfo

func (m *GetPostsPhotosPerParentResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetPostsPhotosPerParentResponse) GetPlacesPhoto() []*PlacePhoto {
	if m != nil {
		return m.PlacesPhoto
	}
	return nil
}

func init() {
	proto.RegisterType((*AddProfilePhotoDBARequest)(nil), "wcity.AddProfilePhotoDBARequest")
	proto.RegisterType((*AddProfilePhotoDBAResponse)(nil), "wcity.AddProfilePhotoDBAResponse")
	proto.RegisterType((*AddCityPhotoDBARequest)(nil), "wcity.AddCityPhotoDBARequest")
	proto.RegisterType((*AddCityPhotoDBAResponse)(nil), "wcity.AddCityPhotoDBAResponse")
	proto.RegisterType((*AddPlacePhotoDBARequest)(nil), "wcity.AddPlacePhotoDBARequest")
	proto.RegisterType((*AddPlacePhotoDBAResponse)(nil), "wcity.AddPlacePhotoDBAResponse")
	proto.RegisterType((*AddPostPhotoDBARequest)(nil), "wcity.AddPostPhotoDBARequest")
	proto.RegisterType((*AddPostPhotoDBAResponse)(nil), "wcity.AddPostPhotoDBAResponse")
	proto.RegisterType((*GetProfilePhotosDBARequest)(nil), "wcity.GetProfilePhotosDBARequest")
	proto.RegisterType((*GetProfilePhotosDBAResponse)(nil), "wcity.GetProfilePhotosDBAResponse")
	proto.RegisterType((*GetCityPhotosDBARequest)(nil), "wcity.GetCityPhotosDBARequest")
	proto.RegisterType((*GetCityPhotosDBAResponse)(nil), "wcity.GetCityPhotosDBAResponse")
	proto.RegisterType((*GetPlacePhotosDBARequest)(nil), "wcity.GetPlacePhotosDBARequest")
	proto.RegisterType((*GetPlacePhotosDBAResponse)(nil), "wcity.GetPlacePhotosDBAResponse")
	proto.RegisterType((*GetPostPhotosDBARequest)(nil), "wcity.GetPostPhotosDBARequest")
	proto.RegisterType((*GetPostPhotosDBAResponse)(nil), "wcity.GetPostPhotosDBAResponse")
	proto.RegisterType((*GetCitysPhotoRequest)(nil), "wcity.GetCitysPhotoRequest")
	proto.RegisterType((*GetCitysPhotoResponse)(nil), "wcity.GetCitysPhotoResponse")
	proto.RegisterType((*GetPlacesPhotosPerCityRequest)(nil), "wcity.GetPlacesPhotosPerCityRequest")
	proto.RegisterType((*GetPlacesPhotosPerCityResponse)(nil), "wcity.GetPlacesPhotosPerCityResponse")
	proto.RegisterType((*GetPostsPhotosPerParentRequest)(nil), "wcity.GetPostsPhotosPerParentRequest")
	proto.RegisterType((*GetPostsPhotosPerParentResponse)(nil), "wcity.GetPostsPhotosPerParentResponse")
}

func init() { proto.RegisterFile("photosdba.proto", fileDescriptor_3d9ff4e76b59f186) }

var fileDescriptor_3d9ff4e76b59f186 = []byte{
	// 808 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0x5d, 0x4f, 0xdb, 0x3c,
	0x14, 0x56, 0x29, 0x05, 0x7a, 0xd0, 0x4b, 0x8b, 0xe1, 0x85, 0x12, 0xbe, 0xba, 0x6c, 0x4c, 0x4c,
	0x43, 0x95, 0x80, 0xdd, 0x6c, 0x77, 0xc0, 0xa6, 0x89, 0x9b, 0x29, 0x0a, 0xec, 0x62, 0xda, 0x34,
	0x14, 0x12, 0x0f, 0x22, 0x15, 0x9a, 0xc5, 0x29, 0x13, 0xd7, 0xfb, 0x27, 0xfb, 0x67, 0xfb, 0x27,
	0x73, 0x1c, 0xc7, 0xb1, 0x53, 0xbb, 0x69, 0xb9, 0x8b, 0x8f, 0xcf, 0xc7, 0x73, 0x3e, 0xfc, 0x9c,
	0x40, 0x2b, 0xba, 0x1d, 0x24, 0x03, 0x12, 0x5c, 0x7b, 0xbd, 0x28, 0xa6, 0x5f, 0xa8, 0xf1, 0xcb,
	0x0f, 0x93, 0x47, 0x0b, 0x31, 0xf9, 0x15, 0xb9, 0xf5, 0x62, 0x1c, 0x64, 0x57, 0xf6, 0x0d, 0x6c,
	0x9c, 0x04, 0x81, 0x13, 0x0f, 0x7e, 0x84, 0x7d, 0xec, 0xa4, 0xf7, 0xef, 0x4f, 0x4f, 0x5c, 0xfc,
	0x73, 0x88, 0x49, 0x82, 0xb6, 0xa0, 0x39, 0x24, 0x38, 0xfe, 0x70, 0xe7, 0x85, 0xfd, 0x4e, 0xad,
	0x5b, 0xdb, 0x6f, 0xba, 0x85, 0x00, 0xb5, 0xa1, 0x3e, 0x8c, 0xfb, 0x9d, 0x19, 0x26, 0x4f, 0x3f,
	0x91, 0x05, 0x0b, 0x04, 0xf7, 0xb1, 0x9f, 0xe0, 0xa0, 0x53, 0xa7, 0xe2, 0x05, 0x57, 0x9c, 0xed,
	0x00, 0x2c, 0x5d, 0x20, 0x12, 0x0d, 0xee, 0x09, 0x46, 0x1d, 0x98, 0x27, 0x43, 0xdf, 0xc7, 0x84,
	0xb0, 0x38, 0x0b, 0x6e, 0x7e, 0x44, 0x4b, 0x30, 0x13, 0x06, 0x2c, 0x48, 0xc3, 0xa5, 0x5f, 0x29,
	0xa6, 0x24, 0xbc, 0xc3, 0x17, 0x89, 0x77, 0x17, 0xb1, 0x20, 0x14, 0x93, 0x10, 0xd8, 0xdf, 0x61,
	0x8d, 0x46, 0x39, 0xa3, 0xd9, 0x96, 0x73, 0x59, 0x83, 0xb9, 0xb4, 0x08, 0xe7, 0x01, 0x0b, 0xd0,
	0x70, 0xf9, 0x69, 0xca, 0x2c, 0x3c, 0x58, 0x1f, 0xf1, 0xff, 0x94, 0x14, 0x2e, 0xcd, 0x29, 0xfc,
	0xae, 0xb1, 0x18, 0x4e, 0xdf, 0xf3, 0x47, 0x1a, 0x42, 0x63, 0x44, 0xa9, 0x5c, 0x64, 0x91, 0x1f,
	0xa7, 0x4b, 0x03, 0x75, 0x61, 0x91, 0x19, 0x9e, 0x65, 0x15, 0x99, 0x65, 0xbe, 0x64, 0x91, 0x7d,
	0x0d, 0x9d, 0x51, 0x10, 0x93, 0x64, 0x4a, 0x44, 0xa6, 0x64, 0xb2, 0x66, 0x39, 0x03, 0x92, 0x68,
	0x9a, 0x15, 0x51, 0x31, 0x4f, 0xb3, 0xe9, 0xf2, 0xd3, 0x94, 0xcd, 0xba, 0xca, 0x0a, 0xa9, 0xf8,
	0xe7, 0x29, 0xd0, 0x00, 0x14, 0x73, 0x91, 0x01, 0x3f, 0x4d, 0x39, 0x6d, 0xef, 0xc0, 0xfa, 0x88,
	0x13, 0x79, 0xa6, 0xc9, 0xa4, 0xaf, 0x87, 0x16, 0x78, 0x53, 0x6b, 0x5b, 0x01, 0xf0, 0x35, 0xad,
	0x0c, 0x53, 0xa6, 0x20, 0xeb, 0xfb, 0x8b, 0x47, 0x2b, 0x3d, 0xf6, 0xb6, 0x7b, 0xb2, 0x23, 0x97,
	0xab, 0xd8, 0x87, 0xb0, 0x4e, 0x63, 0x88, 0x69, 0x25, 0xd5, 0xcf, 0xc1, 0xfe, 0x06, 0x9d, 0x51,
	0x93, 0x0a, 0x4c, 0xfb, 0x25, 0x4c, 0x6d, 0x8e, 0x49, 0x78, 0x11, 0x80, 0xde, 0x30, 0xef, 0xc5,
	0x54, 0x91, 0x49, 0x66, 0x9b, 0xce, 0xc9, 0x86, 0xc6, 0xaa, 0x02, 0xd4, 0xab, 0x12, 0xa8, 0xe5,
	0xbc, 0x50, 0xc2, 0x8d, 0x40, 0x75, 0xcc, 0xca, 0x24, 0xe6, 0x64, 0x0c, 0xa8, 0x66, 0x01, 0x2a,
	0x2b, 0x54, 0xc9, 0xe8, 0x89, 0x85, 0x12, 0x5e, 0x04, 0xa4, 0x03, 0x58, 0xe5, 0x6d, 0x20, 0xd9,
	0x05, 0xc7, 0xb3, 0x0a, 0x8d, 0x07, 0xaf, 0x1f, 0x06, 0xdc, 0x71, 0x76, 0xa0, 0xdc, 0xfa, 0x7f,
	0x49, 0xbb, 0xf2, 0xa5, 0x1e, 0x02, 0xf8, 0xa2, 0xc9, 0xa5, 0x12, 0x49, 0x8e, 0x24, 0x25, 0xfb,
	0x04, 0xb6, 0xf3, 0x36, 0x64, 0xb7, 0xc4, 0xc1, 0x71, 0xaa, 0x9b, 0x83, 0xa3, 0xac, 0xc2, 0xd4,
	0x95, 0x2e, 0xca, 0x22, 0x7b, 0x08, 0x3b, 0x26, 0x17, 0x95, 0x88, 0xdf, 0x72, 0xce, 0x52, 0x20,
	0xaf, 0xcb, 0x5d, 0x25, 0xc5, 0xd8, 0xba, 0xb2, 0x2e, 0x65, 0xed, 0x1d, 0xde, 0xab, 0x22, 0xaa,
	0x43, 0x97, 0xe0, 0x7d, 0x92, 0x43, 0x7f, 0x0e, 0xb3, 0xc9, 0x63, 0x84, 0x59, 0xcc, 0xa5, 0xa3,
	0x96, 0xd4, 0x97, 0x4b, 0x2a, 0x76, 0xd9, 0x65, 0xca, 0x35, 0x11, 0xb3, 0x3a, 0xcf, 0x29, 0x42,
	0x9c, 0xed, 0x08, 0x76, 0x8d, 0x21, 0x2a, 0x53, 0x3b, 0xe6, 0xa9, 0x65, 0xa6, 0xe6, 0x81, 0x95,
	0xb5, 0x8e, 0xfe, 0xce, 0x43, 0x5b, 0x8c, 0xde, 0x05, 0x8e, 0x1f, 0x42, 0x1f, 0xa3, 0x2f, 0x80,
	0x46, 0xb7, 0x2c, 0xea, 0x72, 0x57, 0xc6, 0x4d, 0x6f, 0x3d, 0x1b, 0xa3, 0xc1, 0xe1, 0x3b, 0xd0,
	0x2a, 0xad, 0x3e, 0xb4, 0x5d, 0x58, 0x69, 0x56, 0xae, 0xb5, 0x63, 0xba, 0xe6, 0x1e, 0x2f, 0xa0,
	0x5d, 0xde, 0x31, 0x48, 0xb2, 0xd1, 0x6d, 0x40, 0x6b, 0xd7, 0x78, 0xaf, 0xc0, 0x94, 0x49, 0x5f,
	0x86, 0xa9, 0x59, 0x36, 0x32, 0x4c, 0xed, 0xae, 0xf8, 0x0a, 0xa8, 0xc4, 0xd4, 0xa9, 0xd3, 0xbc,
	0x62, 0xe6, 0x05, 0x60, 0xd9, 0xe3, 0x54, 0xb8, 0x73, 0x17, 0x5a, 0x32, 0xdf, 0xca, 0x25, 0x30,
	0x50, 0xb7, 0x28, 0x81, 0x91, 0xa7, 0x3f, 0x43, 0x5b, 0xe1, 0xcb, 0xd4, 0xa9, 0x64, 0xa4, 0xa5,
	0x5f, 0xab, 0x6b, 0x56, 0x50, 0xa0, 0x2a, 0x95, 0x95, 0xa0, 0xea, 0xe8, 0x53, 0x86, 0xaa, 0x67,
	0xca, 0x4f, 0xb0, 0xac, 0x30, 0x57, 0x7a, 0x89, 0x36, 0xd5, 0x04, 0x15, 0x06, 0xb4, 0xb6, 0xf4,
	0x97, 0xdc, 0xdf, 0x4d, 0xb1, 0x60, 0x72, 0x6a, 0x11, 0x60, 0x5f, 0x94, 0x32, 0xd4, 0x92, 0x98,
	0xb5, 0x57, 0xa1, 0xc5, 0x03, 0x05, 0xb0, 0xa2, 0xbe, 0xf7, 0xf3, 0x20, 0x8d, 0xb1, 0xa7, 0x26,
	0x6c, 0xa0, 0x1b, 0xeb, 0x65, 0x95, 0x5a, 0x16, 0xe5, 0xf4, 0x00, 0x56, 0xc2, 0x41, 0xef, 0x26,
	0x8e, 0x7c, 0x6e, 0xc0, 0xd6, 0xc3, 0xe9, 0x7f, 0x79, 0x4e, 0x4e, 0xfa, 0x0f, 0xef, 0xd4, 0xfe,
	0xcc, 0xd4, 0x5d, 0xe7, 0xec, 0x7a, 0x8e, 0xfd, 0xd2, 0x1f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x69, 0xe7, 0x66, 0xee, 0x00, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PhotosDBAServiceClient is the client API for PhotosDBAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PhotosDBAServiceClient interface {
	AddProfilePhotoDBA(ctx context.Context, in *AddProfilePhotoDBARequest, opts ...grpc.CallOption) (*AddProfilePhotoDBAResponse, error)
	AddCityPhotoDBA(ctx context.Context, in *AddCityPhotoDBARequest, opts ...grpc.CallOption) (*AddCityPhotoDBAResponse, error)
	AddPlacePhotoDBA(ctx context.Context, in *AddPlacePhotoDBARequest, opts ...grpc.CallOption) (*AddPlacePhotoDBAResponse, error)
	AddPostPhotoDBA(ctx context.Context, in *AddPostPhotoDBARequest, opts ...grpc.CallOption) (*AddPostPhotoDBAResponse, error)
	GetProfilePhotoDBA(ctx context.Context, in *GetProfilePhotosDBARequest, opts ...grpc.CallOption) (*GetProfilePhotosDBAResponse, error)
	GetCityPhotoDBA(ctx context.Context, in *GetCityPhotosDBARequest, opts ...grpc.CallOption) (*GetCityPhotosDBAResponse, error)
	GetPlacePhotoDBA(ctx context.Context, in *GetPlacePhotosDBARequest, opts ...grpc.CallOption) (*GetPlacePhotosDBAResponse, error)
	GetPostPhotoDBA(ctx context.Context, in *GetPostPhotosDBARequest, opts ...grpc.CallOption) (*GetPostPhotosDBAResponse, error)
	GetCitysPhotosDBA(ctx context.Context, in *GetCitysPhotoRequest, opts ...grpc.CallOption) (*GetCitysPhotoResponse, error)
	GetPlacesPerCityPhotoDBA(ctx context.Context, in *GetPlacesPhotosPerCityRequest, opts ...grpc.CallOption) (*GetPlacesPhotosPerCityResponse, error)
	GetPostsPhotosIdDBA(ctx context.Context, in *GetPostsPhotosPerParentRequest, opts ...grpc.CallOption) (*GetPostsPhotosPerParentResponse, error)
}

type photosDBAServiceClient struct {
	cc *grpc.ClientConn
}

func NewPhotosDBAServiceClient(cc *grpc.ClientConn) PhotosDBAServiceClient {
	return &photosDBAServiceClient{cc}
}

func (c *photosDBAServiceClient) AddProfilePhotoDBA(ctx context.Context, in *AddProfilePhotoDBARequest, opts ...grpc.CallOption) (*AddProfilePhotoDBAResponse, error) {
	out := new(AddProfilePhotoDBAResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/AddProfilePhotoDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) AddCityPhotoDBA(ctx context.Context, in *AddCityPhotoDBARequest, opts ...grpc.CallOption) (*AddCityPhotoDBAResponse, error) {
	out := new(AddCityPhotoDBAResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/AddCityPhotoDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) AddPlacePhotoDBA(ctx context.Context, in *AddPlacePhotoDBARequest, opts ...grpc.CallOption) (*AddPlacePhotoDBAResponse, error) {
	out := new(AddPlacePhotoDBAResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/AddPlacePhotoDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) AddPostPhotoDBA(ctx context.Context, in *AddPostPhotoDBARequest, opts ...grpc.CallOption) (*AddPostPhotoDBAResponse, error) {
	out := new(AddPostPhotoDBAResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/AddPostPhotoDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) GetProfilePhotoDBA(ctx context.Context, in *GetProfilePhotosDBARequest, opts ...grpc.CallOption) (*GetProfilePhotosDBAResponse, error) {
	out := new(GetProfilePhotosDBAResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/GetProfilePhotoDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) GetCityPhotoDBA(ctx context.Context, in *GetCityPhotosDBARequest, opts ...grpc.CallOption) (*GetCityPhotosDBAResponse, error) {
	out := new(GetCityPhotosDBAResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/GetCityPhotoDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) GetPlacePhotoDBA(ctx context.Context, in *GetPlacePhotosDBARequest, opts ...grpc.CallOption) (*GetPlacePhotosDBAResponse, error) {
	out := new(GetPlacePhotosDBAResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/GetPlacePhotoDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) GetPostPhotoDBA(ctx context.Context, in *GetPostPhotosDBARequest, opts ...grpc.CallOption) (*GetPostPhotosDBAResponse, error) {
	out := new(GetPostPhotosDBAResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/GetPostPhotoDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) GetCitysPhotosDBA(ctx context.Context, in *GetCitysPhotoRequest, opts ...grpc.CallOption) (*GetCitysPhotoResponse, error) {
	out := new(GetCitysPhotoResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/GetCitysPhotosDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) GetPlacesPerCityPhotoDBA(ctx context.Context, in *GetPlacesPhotosPerCityRequest, opts ...grpc.CallOption) (*GetPlacesPhotosPerCityResponse, error) {
	out := new(GetPlacesPhotosPerCityResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/GetPlacesPerCityPhotoDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *photosDBAServiceClient) GetPostsPhotosIdDBA(ctx context.Context, in *GetPostsPhotosPerParentRequest, opts ...grpc.CallOption) (*GetPostsPhotosPerParentResponse, error) {
	out := new(GetPostsPhotosPerParentResponse)
	err := c.cc.Invoke(ctx, "/wcity.PhotosDBAService/GetPostsPhotosIdDBA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhotosDBAServiceServer is the server API for PhotosDBAService service.
type PhotosDBAServiceServer interface {
	AddProfilePhotoDBA(context.Context, *AddProfilePhotoDBARequest) (*AddProfilePhotoDBAResponse, error)
	AddCityPhotoDBA(context.Context, *AddCityPhotoDBARequest) (*AddCityPhotoDBAResponse, error)
	AddPlacePhotoDBA(context.Context, *AddPlacePhotoDBARequest) (*AddPlacePhotoDBAResponse, error)
	AddPostPhotoDBA(context.Context, *AddPostPhotoDBARequest) (*AddPostPhotoDBAResponse, error)
	GetProfilePhotoDBA(context.Context, *GetProfilePhotosDBARequest) (*GetProfilePhotosDBAResponse, error)
	GetCityPhotoDBA(context.Context, *GetCityPhotosDBARequest) (*GetCityPhotosDBAResponse, error)
	GetPlacePhotoDBA(context.Context, *GetPlacePhotosDBARequest) (*GetPlacePhotosDBAResponse, error)
	GetPostPhotoDBA(context.Context, *GetPostPhotosDBARequest) (*GetPostPhotosDBAResponse, error)
	GetCitysPhotosDBA(context.Context, *GetCitysPhotoRequest) (*GetCitysPhotoResponse, error)
	GetPlacesPerCityPhotoDBA(context.Context, *GetPlacesPhotosPerCityRequest) (*GetPlacesPhotosPerCityResponse, error)
	GetPostsPhotosIdDBA(context.Context, *GetPostsPhotosPerParentRequest) (*GetPostsPhotosPerParentResponse, error)
}

// UnimplementedPhotosDBAServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPhotosDBAServiceServer struct {
}

func (*UnimplementedPhotosDBAServiceServer) AddProfilePhotoDBA(ctx context.Context, req *AddProfilePhotoDBARequest) (*AddProfilePhotoDBAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProfilePhotoDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) AddCityPhotoDBA(ctx context.Context, req *AddCityPhotoDBARequest) (*AddCityPhotoDBAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCityPhotoDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) AddPlacePhotoDBA(ctx context.Context, req *AddPlacePhotoDBARequest) (*AddPlacePhotoDBAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPlacePhotoDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) AddPostPhotoDBA(ctx context.Context, req *AddPostPhotoDBARequest) (*AddPostPhotoDBAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPostPhotoDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) GetProfilePhotoDBA(ctx context.Context, req *GetProfilePhotosDBARequest) (*GetProfilePhotosDBAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfilePhotoDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) GetCityPhotoDBA(ctx context.Context, req *GetCityPhotosDBARequest) (*GetCityPhotosDBAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCityPhotoDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) GetPlacePhotoDBA(ctx context.Context, req *GetPlacePhotosDBARequest) (*GetPlacePhotosDBAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlacePhotoDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) GetPostPhotoDBA(ctx context.Context, req *GetPostPhotosDBARequest) (*GetPostPhotosDBAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostPhotoDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) GetCitysPhotosDBA(ctx context.Context, req *GetCitysPhotoRequest) (*GetCitysPhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCitysPhotosDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) GetPlacesPerCityPhotoDBA(ctx context.Context, req *GetPlacesPhotosPerCityRequest) (*GetPlacesPhotosPerCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlacesPerCityPhotoDBA not implemented")
}
func (*UnimplementedPhotosDBAServiceServer) GetPostsPhotosIdDBA(ctx context.Context, req *GetPostsPhotosPerParentRequest) (*GetPostsPhotosPerParentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostsPhotosIdDBA not implemented")
}

func RegisterPhotosDBAServiceServer(s *grpc.Server, srv PhotosDBAServiceServer) {
	s.RegisterService(&_PhotosDBAService_serviceDesc, srv)
}

func _PhotosDBAService_AddProfilePhotoDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProfilePhotoDBARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).AddProfilePhotoDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/AddProfilePhotoDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).AddProfilePhotoDBA(ctx, req.(*AddProfilePhotoDBARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_AddCityPhotoDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCityPhotoDBARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).AddCityPhotoDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/AddCityPhotoDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).AddCityPhotoDBA(ctx, req.(*AddCityPhotoDBARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_AddPlacePhotoDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPlacePhotoDBARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).AddPlacePhotoDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/AddPlacePhotoDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).AddPlacePhotoDBA(ctx, req.(*AddPlacePhotoDBARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_AddPostPhotoDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPostPhotoDBARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).AddPostPhotoDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/AddPostPhotoDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).AddPostPhotoDBA(ctx, req.(*AddPostPhotoDBARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_GetProfilePhotoDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfilePhotosDBARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).GetProfilePhotoDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/GetProfilePhotoDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).GetProfilePhotoDBA(ctx, req.(*GetProfilePhotosDBARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_GetCityPhotoDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCityPhotosDBARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).GetCityPhotoDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/GetCityPhotoDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).GetCityPhotoDBA(ctx, req.(*GetCityPhotosDBARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_GetPlacePhotoDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlacePhotosDBARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).GetPlacePhotoDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/GetPlacePhotoDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).GetPlacePhotoDBA(ctx, req.(*GetPlacePhotosDBARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_GetPostPhotoDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostPhotosDBARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).GetPostPhotoDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/GetPostPhotoDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).GetPostPhotoDBA(ctx, req.(*GetPostPhotosDBARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_GetCitysPhotosDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCitysPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).GetCitysPhotosDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/GetCitysPhotosDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).GetCitysPhotosDBA(ctx, req.(*GetCitysPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_GetPlacesPerCityPhotoDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlacesPhotosPerCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).GetPlacesPerCityPhotoDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/GetPlacesPerCityPhotoDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).GetPlacesPerCityPhotoDBA(ctx, req.(*GetPlacesPhotosPerCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhotosDBAService_GetPostsPhotosIdDBA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostsPhotosPerParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhotosDBAServiceServer).GetPostsPhotosIdDBA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PhotosDBAService/GetPostsPhotosIdDBA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhotosDBAServiceServer).GetPostsPhotosIdDBA(ctx, req.(*GetPostsPhotosPerParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PhotosDBAService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wcity.PhotosDBAService",
	HandlerType: (*PhotosDBAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProfilePhotoDBA",
			Handler:    _PhotosDBAService_AddProfilePhotoDBA_Handler,
		},
		{
			MethodName: "AddCityPhotoDBA",
			Handler:    _PhotosDBAService_AddCityPhotoDBA_Handler,
		},
		{
			MethodName: "AddPlacePhotoDBA",
			Handler:    _PhotosDBAService_AddPlacePhotoDBA_Handler,
		},
		{
			MethodName: "AddPostPhotoDBA",
			Handler:    _PhotosDBAService_AddPostPhotoDBA_Handler,
		},
		{
			MethodName: "GetProfilePhotoDBA",
			Handler:    _PhotosDBAService_GetProfilePhotoDBA_Handler,
		},
		{
			MethodName: "GetCityPhotoDBA",
			Handler:    _PhotosDBAService_GetCityPhotoDBA_Handler,
		},
		{
			MethodName: "GetPlacePhotoDBA",
			Handler:    _PhotosDBAService_GetPlacePhotoDBA_Handler,
		},
		{
			MethodName: "GetPostPhotoDBA",
			Handler:    _PhotosDBAService_GetPostPhotoDBA_Handler,
		},
		{
			MethodName: "GetCitysPhotosDBA",
			Handler:    _PhotosDBAService_GetCitysPhotosDBA_Handler,
		},
		{
			MethodName: "GetPlacesPerCityPhotoDBA",
			Handler:    _PhotosDBAService_GetPlacesPerCityPhotoDBA_Handler,
		},
		{
			MethodName: "GetPostsPhotosIdDBA",
			Handler:    _PhotosDBAService_GetPostsPhotosIdDBA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "photosdba.proto",
}
