// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package wcity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CityPost struct {
	IndexId              int32    `protobuf:"varint,1,opt,name=indexId,proto3" json:"indexId,omitempty"`
	CreatorEmail         string   `protobuf:"bytes,2,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	CityName             string   `protobuf:"bytes,3,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CityCountry          string   `protobuf:"bytes,4,opt,name=cityCountry,proto3" json:"cityCountry,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	TimeStamp            string   `protobuf:"bytes,7,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Likes                []string `protobuf:"bytes,8,rep,name=likes,proto3" json:"likes,omitempty"`
	MongoId              string   `protobuf:"bytes,9,opt,name=mongoId,proto3" json:"mongoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityPost) Reset()         { *m = CityPost{} }
func (m *CityPost) String() string { return proto.CompactTextString(m) }
func (*CityPost) ProtoMessage()    {}
func (*CityPost) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *CityPost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityPost.Unmarshal(m, b)
}
func (m *CityPost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityPost.Marshal(b, m, deterministic)
}
func (m *CityPost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityPost.Merge(m, src)
}
func (m *CityPost) XXX_Size() int {
	return xxx_messageInfo_CityPost.Size(m)
}
func (m *CityPost) XXX_DiscardUnknown() {
	xxx_messageInfo_CityPost.DiscardUnknown(m)
}

var xxx_messageInfo_CityPost proto.InternalMessageInfo

func (m *CityPost) GetIndexId() int32 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

func (m *CityPost) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

func (m *CityPost) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *CityPost) GetCityCountry() string {
	if m != nil {
		return m.CityCountry
	}
	return ""
}

func (m *CityPost) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CityPost) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CityPost) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func (m *CityPost) GetLikes() []string {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *CityPost) GetMongoId() string {
	if m != nil {
		return m.MongoId
	}
	return ""
}

type PlacePost struct {
	IndexId              int32    `protobuf:"varint,1,opt,name=indexId,proto3" json:"indexId,omitempty"`
	CreatorEmail         string   `protobuf:"bytes,2,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	CityName             string   `protobuf:"bytes,3,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CountryName          string   `protobuf:"bytes,4,opt,name=countryName,proto3" json:"countryName,omitempty"`
	PlaceName            string   `protobuf:"bytes,5,opt,name=placeName,proto3" json:"placeName,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	TimeStamp            string   `protobuf:"bytes,8,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Likes                []string `protobuf:"bytes,9,rep,name=likes,proto3" json:"likes,omitempty"`
	MongoId              string   `protobuf:"bytes,10,opt,name=mongoId,proto3" json:"mongoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlacePost) Reset()         { *m = PlacePost{} }
func (m *PlacePost) String() string { return proto.CompactTextString(m) }
func (*PlacePost) ProtoMessage()    {}
func (*PlacePost) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *PlacePost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacePost.Unmarshal(m, b)
}
func (m *PlacePost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacePost.Marshal(b, m, deterministic)
}
func (m *PlacePost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacePost.Merge(m, src)
}
func (m *PlacePost) XXX_Size() int {
	return xxx_messageInfo_PlacePost.Size(m)
}
func (m *PlacePost) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacePost.DiscardUnknown(m)
}

var xxx_messageInfo_PlacePost proto.InternalMessageInfo

func (m *PlacePost) GetIndexId() int32 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

func (m *PlacePost) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

func (m *PlacePost) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *PlacePost) GetCountryName() string {
	if m != nil {
		return m.CountryName
	}
	return ""
}

func (m *PlacePost) GetPlaceName() string {
	if m != nil {
		return m.PlaceName
	}
	return ""
}

func (m *PlacePost) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PlacePost) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *PlacePost) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

func (m *PlacePost) GetLikes() []string {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *PlacePost) GetMongoId() string {
	if m != nil {
		return m.MongoId
	}
	return ""
}

type CreatePostResponse struct {
	Valied               bool     `protobuf:"varint,1,opt,name=valied,proto3" json:"valied,omitempty"`
	IndexId              int32    `protobuf:"varint,2,opt,name=indexId,proto3" json:"indexId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetValied() bool {
	if m != nil {
		return m.Valied
	}
	return false
}

func (m *CreatePostResponse) GetIndexId() int32 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

type PostsRequest struct {
	IndexId              int32    `protobuf:"varint,1,opt,name=indexId,proto3" json:"indexId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostsRequest) Reset()         { *m = PostsRequest{} }
func (m *PostsRequest) String() string { return proto.CompactTextString(m) }
func (*PostsRequest) ProtoMessage()    {}
func (*PostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *PostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostsRequest.Unmarshal(m, b)
}
func (m *PostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostsRequest.Marshal(b, m, deterministic)
}
func (m *PostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostsRequest.Merge(m, src)
}
func (m *PostsRequest) XXX_Size() int {
	return xxx_messageInfo_PostsRequest.Size(m)
}
func (m *PostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostsRequest proto.InternalMessageInfo

func (m *PostsRequest) GetIndexId() int32 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

type CityPostsResponse struct {
	Valid                bool        `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	IndexId              int32       `protobuf:"varint,2,opt,name=indexId,proto3" json:"indexId,omitempty"`
	Posts                []*CityPost `protobuf:"bytes,3,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CityPostsResponse) Reset()         { *m = CityPostsResponse{} }
func (m *CityPostsResponse) String() string { return proto.CompactTextString(m) }
func (*CityPostsResponse) ProtoMessage()    {}
func (*CityPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *CityPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityPostsResponse.Unmarshal(m, b)
}
func (m *CityPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityPostsResponse.Marshal(b, m, deterministic)
}
func (m *CityPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityPostsResponse.Merge(m, src)
}
func (m *CityPostsResponse) XXX_Size() int {
	return xxx_messageInfo_CityPostsResponse.Size(m)
}
func (m *CityPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CityPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CityPostsResponse proto.InternalMessageInfo

func (m *CityPostsResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CityPostsResponse) GetIndexId() int32 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

func (m *CityPostsResponse) GetPosts() []*CityPost {
	if m != nil {
		return m.Posts
	}
	return nil
}

type PlacePostsResponse struct {
	Valid                bool         `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	IndexId              int32        `protobuf:"varint,2,opt,name=indexId,proto3" json:"indexId,omitempty"`
	Posts                []*PlacePost `protobuf:"bytes,3,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PlacePostsResponse) Reset()         { *m = PlacePostsResponse{} }
func (m *PlacePostsResponse) String() string { return proto.CompactTextString(m) }
func (*PlacePostsResponse) ProtoMessage()    {}
func (*PlacePostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *PlacePostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacePostsResponse.Unmarshal(m, b)
}
func (m *PlacePostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacePostsResponse.Marshal(b, m, deterministic)
}
func (m *PlacePostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacePostsResponse.Merge(m, src)
}
func (m *PlacePostsResponse) XXX_Size() int {
	return xxx_messageInfo_PlacePostsResponse.Size(m)
}
func (m *PlacePostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacePostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlacePostsResponse proto.InternalMessageInfo

func (m *PlacePostsResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *PlacePostsResponse) GetIndexId() int32 {
	if m != nil {
		return m.IndexId
	}
	return 0
}

func (m *PlacePostsResponse) GetPosts() []*PlacePost {
	if m != nil {
		return m.Posts
	}
	return nil
}

type UpdatePostRequest struct {
	MongoId              string   `protobuf:"bytes,1,opt,name=mongoId,proto3" json:"mongoId,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{6}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetMongoId() string {
	if m != nil {
		return m.MongoId
	}
	return ""
}

func (m *UpdatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdatePostResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{7}
}

func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(m, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

func (m *UpdatePostResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*CityPost)(nil), "wcity.CityPost")
	proto.RegisterType((*PlacePost)(nil), "wcity.PlacePost")
	proto.RegisterType((*CreatePostResponse)(nil), "wcity.CreatePostResponse")
	proto.RegisterType((*PostsRequest)(nil), "wcity.PostsRequest")
	proto.RegisterType((*CityPostsResponse)(nil), "wcity.CityPostsResponse")
	proto.RegisterType((*PlacePostsResponse)(nil), "wcity.PlacePostsResponse")
	proto.RegisterType((*UpdatePostRequest)(nil), "wcity.UpdatePostRequest")
	proto.RegisterType((*UpdatePostResponse)(nil), "wcity.UpdatePostResponse")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1) }

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xd5, 0x64, 0x69, 0x93, 0xb7, 0xb2, 0x32, 0x83, 0x90, 0x5b, 0x71, 0xa8, 0x22, 0x81,
	0x2a, 0x0e, 0x39, 0x8c, 0x2b, 0xe2, 0xb0, 0x6a, 0x43, 0x5c, 0x50, 0x94, 0x09, 0x71, 0xce, 0x52,
	0x6b, 0x32, 0x24, 0x75, 0x48, 0xbc, 0x41, 0xff, 0x16, 0xc4, 0x85, 0x3f, 0x14, 0x11, 0xdb, 0xb1,
	0x9d, 0xf4, 0xd7, 0x61, 0x07, 0x6e, 0x79, 0xef, 0xf9, 0xbd, 0xe7, 0xf7, 0xf9, 0xbe, 0x18, 0xa0,
	0x64, 0x35, 0x8f, 0xca, 0x8a, 0x71, 0x86, 0xbc, 0x1f, 0x19, 0xe5, 0x9b, 0xf0, 0xef, 0x00, 0xfc,
	0x65, 0xf3, 0x11, 0x37, 0x11, 0x84, 0x61, 0x44, 0xd7, 0x2b, 0xf2, 0xf3, 0xe3, 0x0a, 0x0f, 0xe6,
	0x83, 0x85, 0x97, 0x68, 0x13, 0x85, 0x30, 0xce, 0x2a, 0x92, 0x72, 0x56, 0x5d, 0x15, 0x29, 0xcd,
	0xb1, 0xd3, 0x84, 0x83, 0xa4, 0xe7, 0x43, 0x33, 0xf0, 0x45, 0xc9, 0x4f, 0x69, 0x41, 0xb0, 0x2b,
	0xe3, 0xc6, 0x46, 0x73, 0x38, 0x15, 0xdf, 0x4b, 0x76, 0xbf, 0xe6, 0xd5, 0x06, 0x9f, 0xc8, 0x70,
	0xd7, 0x85, 0x9e, 0x83, 0xc7, 0x29, 0xcf, 0x09, 0xf6, 0x64, 0x4c, 0x19, 0x08, 0xc1, 0xc9, 0x2d,
	0x5b, 0x6d, 0xf0, 0x50, 0x3a, 0xe5, 0x37, 0x7a, 0x09, 0x01, 0xa7, 0x05, 0xb9, 0xe1, 0x69, 0x51,
	0xe2, 0x91, 0x0c, 0x58, 0x87, 0xa8, 0x93, 0xd3, 0x6f, 0xa4, 0xc6, 0xfe, 0xdc, 0x15, 0x75, 0xa4,
	0x21, 0x26, 0x2b, 0xd8, 0xfa, 0x8e, 0x35, 0x93, 0x05, 0x32, 0x43, 0x9b, 0xe1, 0x6f, 0x07, 0x82,
	0x38, 0x4f, 0x33, 0xf2, 0x1f, 0x08, 0xa8, 0x51, 0x65, 0x58, 0x13, 0xb0, 0x2e, 0x31, 0x57, 0x29,
	0x2e, 0x22, 0xe3, 0x8a, 0x82, 0x75, 0x58, 0x3e, 0xc3, 0x7d, 0x7c, 0x46, 0x87, 0xf8, 0xf8, 0x07,
	0xf9, 0x04, 0x07, 0xf8, 0x40, 0x9f, 0xcf, 0x35, 0xa0, 0xa5, 0x98, 0x51, 0xf2, 0x49, 0x48, 0x5d,
	0xb2, 0x75, 0x4d, 0xd0, 0x0b, 0x18, 0x3e, 0xa4, 0x39, 0x25, 0x0a, 0x93, 0x9f, 0xb4, 0x56, 0x97,
	0x9f, 0xd3, 0xe3, 0x17, 0x2e, 0x60, 0x2c, 0x2a, 0xd4, 0x09, 0xf9, 0x7e, 0x4f, 0x8e, 0x91, 0x0e,
	0xbf, 0xc2, 0xb9, 0xde, 0xc8, 0xda, 0x34, 0x6c, 0xae, 0x2d, 0x5a, 0xe8, 0x7e, 0xca, 0x38, 0xdc,
	0x0e, 0xbd, 0x02, 0x4f, 0x2c, 0x7b, 0xdd, 0xe8, 0xe0, 0x2e, 0x4e, 0x2f, 0x26, 0x91, 0x5c, 0xf7,
	0x48, 0x17, 0x4e, 0x54, 0x34, 0xcc, 0x01, 0x19, 0xf1, 0x1f, 0xdf, 0xec, 0x75, 0xbf, 0xd9, 0xd3,
	0xb6, 0x99, 0xa9, 0xac, 0xbb, 0x7d, 0x81, 0xf3, 0xcf, 0xe5, 0xca, 0xb0, 0x34, 0x20, 0x34, 0xfa,
	0x41, 0x0f, 0xbd, 0x95, 0xdc, 0xd9, 0x27, 0xb9, 0x6b, 0x25, 0x0f, 0xdf, 0x00, 0xea, 0x16, 0x3e,
	0x36, 0xc6, 0xc5, 0x2f, 0xb7, 0x55, 0xe2, 0x86, 0x54, 0x0f, 0x34, 0x23, 0xe8, 0x1d, 0x9c, 0x29,
	0x85, 0xcd, 0x3b, 0xb0, 0x4d, 0x6b, 0x36, 0xd5, 0x8e, 0xdd, 0x4d, 0x78, 0x0f, 0x93, 0xd6, 0x6b,
	0x7e, 0xa2, 0x9d, 0xf9, 0x8f, 0xe7, 0x3f, 0xf9, 0x40, 0xb8, 0x15, 0x01, 0x3d, 0xd3, 0xd9, 0x9d,
	0x6d, 0x99, 0xe1, 0xad, 0x1b, 0xd5, 0x9d, 0xfc, 0x71, 0x93, 0x6f, 0xfc, 0xfb, 0xd3, 0xa7, 0xdb,
	0x37, 0xb2, 0xf9, 0xd7, 0x30, 0x69, 0xd1, 0xd9, 0x47, 0xa0, 0x3d, 0xbd, 0xa3, 0x95, 0xa9, 0xb3,
	0x07, 0xf6, 0x15, 0x9c, 0x29, 0xaf, 0x7d, 0x4d, 0x1f, 0x51, 0xe6, 0x32, 0x82, 0x29, 0x65, 0xd1,
	0x5d, 0x55, 0x66, 0xed, 0x19, 0xb9, 0x39, 0x4a, 0xa9, 0xcb, 0x40, 0x1c, 0x8d, 0xc5, 0xf3, 0x1d,
	0x0f, 0xfe, 0x38, 0x6e, 0x12, 0x2f, 0x6f, 0x87, 0xf2, 0x35, 0x7f, 0xfb, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x4f, 0x7f, 0x2d, 0xff, 0xdb, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsServiceClient interface {
	CreateCityPost(ctx context.Context, in *CityPost, opts ...grpc.CallOption) (*CreatePostResponse, error)
	CreatePlacePost(ctx context.Context, in *PlacePost, opts ...grpc.CallOption) (*CreatePostResponse, error)
	GetPlacePosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*CityPostsResponse, error)
	GetCityPosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*PlacePostsResponse, error)
	UpdatePlacePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	UpdateCityPost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error)
}

type postsServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostsServiceClient(cc *grpc.ClientConn) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) CreateCityPost(ctx context.Context, in *CityPost, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/wcity.PostsService/CreateCityPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) CreatePlacePost(ctx context.Context, in *PlacePost, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/wcity.PostsService/CreatePlacePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPlacePosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*CityPostsResponse, error) {
	out := new(CityPostsResponse)
	err := c.cc.Invoke(ctx, "/wcity.PostsService/GetPlacePosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetCityPosts(ctx context.Context, in *PostsRequest, opts ...grpc.CallOption) (*PlacePostsResponse, error) {
	out := new(PlacePostsResponse)
	err := c.cc.Invoke(ctx, "/wcity.PostsService/GetCityPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) UpdatePlacePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/wcity.PostsService/UpdatePlacePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) UpdateCityPost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/wcity.PostsService/UpdateCityPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
type PostsServiceServer interface {
	CreateCityPost(context.Context, *CityPost) (*CreatePostResponse, error)
	CreatePlacePost(context.Context, *PlacePost) (*CreatePostResponse, error)
	GetPlacePosts(context.Context, *PostsRequest) (*CityPostsResponse, error)
	GetCityPosts(context.Context, *PostsRequest) (*PlacePostsResponse, error)
	UpdatePlacePost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
	UpdateCityPost(context.Context, *UpdatePostRequest) (*UpdatePostResponse, error)
}

// UnimplementedPostsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostsServiceServer struct {
}

func (*UnimplementedPostsServiceServer) CreateCityPost(ctx context.Context, req *CityPost) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCityPost not implemented")
}
func (*UnimplementedPostsServiceServer) CreatePlacePost(ctx context.Context, req *PlacePost) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlacePost not implemented")
}
func (*UnimplementedPostsServiceServer) GetPlacePosts(ctx context.Context, req *PostsRequest) (*CityPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlacePosts not implemented")
}
func (*UnimplementedPostsServiceServer) GetCityPosts(ctx context.Context, req *PostsRequest) (*PlacePostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCityPosts not implemented")
}
func (*UnimplementedPostsServiceServer) UpdatePlacePost(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlacePost not implemented")
}
func (*UnimplementedPostsServiceServer) UpdateCityPost(ctx context.Context, req *UpdatePostRequest) (*UpdatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCityPost not implemented")
}

func RegisterPostsServiceServer(s *grpc.Server, srv PostsServiceServer) {
	s.RegisterService(&_PostsService_serviceDesc, srv)
}

func _PostsService_CreateCityPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).CreateCityPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PostsService/CreateCityPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).CreateCityPost(ctx, req.(*CityPost))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_CreatePlacePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlacePost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).CreatePlacePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PostsService/CreatePlacePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).CreatePlacePost(ctx, req.(*PlacePost))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPlacePosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPlacePosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PostsService/GetPlacePosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPlacePosts(ctx, req.(*PostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetCityPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetCityPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PostsService/GetCityPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetCityPosts(ctx, req.(*PostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_UpdatePlacePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).UpdatePlacePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PostsService/UpdatePlacePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).UpdatePlacePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_UpdateCityPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).UpdateCityPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.PostsService/UpdateCityPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).UpdateCityPost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wcity.PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCityPost",
			Handler:    _PostsService_CreateCityPost_Handler,
		},
		{
			MethodName: "CreatePlacePost",
			Handler:    _PostsService_CreatePlacePost_Handler,
		},
		{
			MethodName: "GetPlacePosts",
			Handler:    _PostsService_GetPlacePosts_Handler,
		},
		{
			MethodName: "GetCityPosts",
			Handler:    _PostsService_GetCityPosts_Handler,
		},
		{
			MethodName: "UpdatePlacePost",
			Handler:    _PostsService_UpdatePlacePost_Handler,
		},
		{
			MethodName: "UpdateCityPost",
			Handler:    _PostsService_UpdateCityPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
