// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profilesdb.proto

package wcity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserResponsePDB struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponsePDB) Reset()         { *m = CreateUserResponsePDB{} }
func (m *CreateUserResponsePDB) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponsePDB) ProtoMessage()    {}
func (*CreateUserResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{0}
}

func (m *CreateUserResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponsePDB.Unmarshal(m, b)
}
func (m *CreateUserResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponsePDB.Marshal(b, m, deterministic)
}
func (m *CreateUserResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponsePDB.Merge(m, src)
}
func (m *CreateUserResponsePDB) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponsePDB.Size(m)
}
func (m *CreateUserResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponsePDB proto.InternalMessageInfo

func (m *CreateUserResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CreateUserResponsePDB) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserRequestPDB struct {
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequestPDB) Reset()         { *m = GetUserRequestPDB{} }
func (m *GetUserRequestPDB) String() string { return proto.CompactTextString(m) }
func (*GetUserRequestPDB) ProtoMessage()    {}
func (*GetUserRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{1}
}

func (m *GetUserRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequestPDB.Unmarshal(m, b)
}
func (m *GetUserRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequestPDB.Marshal(b, m, deterministic)
}
func (m *GetUserRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequestPDB.Merge(m, src)
}
func (m *GetUserRequestPDB) XXX_Size() int {
	return xxx_messageInfo_GetUserRequestPDB.Size(m)
}
func (m *GetUserRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequestPDB proto.InternalMessageInfo

func (m *GetUserRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserResponsePDB struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponsePDB) Reset()         { *m = UserResponsePDB{} }
func (m *UserResponsePDB) String() string { return proto.CompactTextString(m) }
func (*UserResponsePDB) ProtoMessage()    {}
func (*UserResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{2}
}

func (m *UserResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponsePDB.Unmarshal(m, b)
}
func (m *UserResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponsePDB.Marshal(b, m, deterministic)
}
func (m *UserResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponsePDB.Merge(m, src)
}
func (m *UserResponsePDB) XXX_Size() int {
	return xxx_messageInfo_UserResponsePDB.Size(m)
}
func (m *UserResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponsePDB proto.InternalMessageInfo

func (m *UserResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *UserResponsePDB) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CityRequestPDB struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityRequestPDB) Reset()         { *m = CityRequestPDB{} }
func (m *CityRequestPDB) String() string { return proto.CompactTextString(m) }
func (*CityRequestPDB) ProtoMessage()    {}
func (*CityRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{3}
}

func (m *CityRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityRequestPDB.Unmarshal(m, b)
}
func (m *CityRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityRequestPDB.Marshal(b, m, deterministic)
}
func (m *CityRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityRequestPDB.Merge(m, src)
}
func (m *CityRequestPDB) XXX_Size() int {
	return xxx_messageInfo_CityRequestPDB.Size(m)
}
func (m *CityRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityRequestPDB proto.InternalMessageInfo

func (m *CityRequestPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CityRequestPDB) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type CityResponsePDB struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	City                 *City    `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityResponsePDB) Reset()         { *m = CityResponsePDB{} }
func (m *CityResponsePDB) String() string { return proto.CompactTextString(m) }
func (*CityResponsePDB) ProtoMessage()    {}
func (*CityResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{4}
}

func (m *CityResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityResponsePDB.Unmarshal(m, b)
}
func (m *CityResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityResponsePDB.Marshal(b, m, deterministic)
}
func (m *CityResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityResponsePDB.Merge(m, src)
}
func (m *CityResponsePDB) XXX_Size() int {
	return xxx_messageInfo_CityResponsePDB.Size(m)
}
func (m *CityResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityResponsePDB proto.InternalMessageInfo

func (m *CityResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CityResponsePDB) GetCity() *City {
	if m != nil {
		return m.City
	}
	return nil
}

type PlaceRequestPDB struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceRequestPDB) Reset()         { *m = PlaceRequestPDB{} }
func (m *PlaceRequestPDB) String() string { return proto.CompactTextString(m) }
func (*PlaceRequestPDB) ProtoMessage()    {}
func (*PlaceRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{5}
}

func (m *PlaceRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceRequestPDB.Unmarshal(m, b)
}
func (m *PlaceRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceRequestPDB.Marshal(b, m, deterministic)
}
func (m *PlaceRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceRequestPDB.Merge(m, src)
}
func (m *PlaceRequestPDB) XXX_Size() int {
	return xxx_messageInfo_PlaceRequestPDB.Size(m)
}
func (m *PlaceRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceRequestPDB proto.InternalMessageInfo

func (m *PlaceRequestPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaceRequestPDB) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *PlaceRequestPDB) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type PlaceResponsePDB struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Place                *Place   `protobuf:"bytes,2,opt,name=place,proto3" json:"place,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceResponsePDB) Reset()         { *m = PlaceResponsePDB{} }
func (m *PlaceResponsePDB) String() string { return proto.CompactTextString(m) }
func (*PlaceResponsePDB) ProtoMessage()    {}
func (*PlaceResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{6}
}

func (m *PlaceResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceResponsePDB.Unmarshal(m, b)
}
func (m *PlaceResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceResponsePDB.Marshal(b, m, deterministic)
}
func (m *PlaceResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceResponsePDB.Merge(m, src)
}
func (m *PlaceResponsePDB) XXX_Size() int {
	return xxx_messageInfo_PlaceResponsePDB.Size(m)
}
func (m *PlaceResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceResponsePDB proto.InternalMessageInfo

func (m *PlaceResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *PlaceResponsePDB) GetPlace() *Place {
	if m != nil {
		return m.Place
	}
	return nil
}

type UpdatedUserRequestPDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatedUserRequestPDB) Reset()         { *m = UpdatedUserRequestPDB{} }
func (m *UpdatedUserRequestPDB) String() string { return proto.CompactTextString(m) }
func (*UpdatedUserRequestPDB) ProtoMessage()    {}
func (*UpdatedUserRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{7}
}

func (m *UpdatedUserRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatedUserRequestPDB.Unmarshal(m, b)
}
func (m *UpdatedUserRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatedUserRequestPDB.Marshal(b, m, deterministic)
}
func (m *UpdatedUserRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatedUserRequestPDB.Merge(m, src)
}
func (m *UpdatedUserRequestPDB) XXX_Size() int {
	return xxx_messageInfo_UpdatedUserRequestPDB.Size(m)
}
func (m *UpdatedUserRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatedUserRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatedUserRequestPDB proto.InternalMessageInfo

func (m *UpdatedUserRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdatedUserRequestPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatedUserRequestPDB) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type VisitedCitysRequestPDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitedCitysRequestPDB) Reset()         { *m = VisitedCitysRequestPDB{} }
func (m *VisitedCitysRequestPDB) String() string { return proto.CompactTextString(m) }
func (*VisitedCitysRequestPDB) ProtoMessage()    {}
func (*VisitedCitysRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{8}
}

func (m *VisitedCitysRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitedCitysRequestPDB.Unmarshal(m, b)
}
func (m *VisitedCitysRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitedCitysRequestPDB.Marshal(b, m, deterministic)
}
func (m *VisitedCitysRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitedCitysRequestPDB.Merge(m, src)
}
func (m *VisitedCitysRequestPDB) XXX_Size() int {
	return xxx_messageInfo_VisitedCitysRequestPDB.Size(m)
}
func (m *VisitedCitysRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitedCitysRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitedCitysRequestPDB proto.InternalMessageInfo

func (m *VisitedCitysRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type VisitedCitysResponsePDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Citys                []*City  `protobuf:"bytes,2,rep,name=citys,proto3" json:"citys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitedCitysResponsePDB) Reset()         { *m = VisitedCitysResponsePDB{} }
func (m *VisitedCitysResponsePDB) String() string { return proto.CompactTextString(m) }
func (*VisitedCitysResponsePDB) ProtoMessage()    {}
func (*VisitedCitysResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{9}
}

func (m *VisitedCitysResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitedCitysResponsePDB.Unmarshal(m, b)
}
func (m *VisitedCitysResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitedCitysResponsePDB.Marshal(b, m, deterministic)
}
func (m *VisitedCitysResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitedCitysResponsePDB.Merge(m, src)
}
func (m *VisitedCitysResponsePDB) XXX_Size() int {
	return xxx_messageInfo_VisitedCitysResponsePDB.Size(m)
}
func (m *VisitedCitysResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitedCitysResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitedCitysResponsePDB proto.InternalMessageInfo

func (m *VisitedCitysResponsePDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VisitedCitysResponsePDB) GetCitys() []*City {
	if m != nil {
		return m.Citys
	}
	return nil
}

type VisitCityRequestPDB struct {
	UserEmail            string   `protobuf:"bytes,1,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	CityId               int32    `protobuf:"varint,2,opt,name=cityId,proto3" json:"cityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitCityRequestPDB) Reset()         { *m = VisitCityRequestPDB{} }
func (m *VisitCityRequestPDB) String() string { return proto.CompactTextString(m) }
func (*VisitCityRequestPDB) ProtoMessage()    {}
func (*VisitCityRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{10}
}

func (m *VisitCityRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitCityRequestPDB.Unmarshal(m, b)
}
func (m *VisitCityRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitCityRequestPDB.Marshal(b, m, deterministic)
}
func (m *VisitCityRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitCityRequestPDB.Merge(m, src)
}
func (m *VisitCityRequestPDB) XXX_Size() int {
	return xxx_messageInfo_VisitCityRequestPDB.Size(m)
}
func (m *VisitCityRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitCityRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitCityRequestPDB proto.InternalMessageInfo

func (m *VisitCityRequestPDB) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *VisitCityRequestPDB) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type VisitCityResponsePDB struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	TimeStamp            string   `protobuf:"bytes,2,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitCityResponsePDB) Reset()         { *m = VisitCityResponsePDB{} }
func (m *VisitCityResponsePDB) String() string { return proto.CompactTextString(m) }
func (*VisitCityResponsePDB) ProtoMessage()    {}
func (*VisitCityResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{11}
}

func (m *VisitCityResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitCityResponsePDB.Unmarshal(m, b)
}
func (m *VisitCityResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitCityResponsePDB.Marshal(b, m, deterministic)
}
func (m *VisitCityResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitCityResponsePDB.Merge(m, src)
}
func (m *VisitCityResponsePDB) XXX_Size() int {
	return xxx_messageInfo_VisitCityResponsePDB.Size(m)
}
func (m *VisitCityResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitCityResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitCityResponsePDB proto.InternalMessageInfo

func (m *VisitCityResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *VisitCityResponsePDB) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

type CityPlacesRequestPDB struct {
	CityId               int32    `protobuf:"varint,1,opt,name=cityId,proto3" json:"cityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityPlacesRequestPDB) Reset()         { *m = CityPlacesRequestPDB{} }
func (m *CityPlacesRequestPDB) String() string { return proto.CompactTextString(m) }
func (*CityPlacesRequestPDB) ProtoMessage()    {}
func (*CityPlacesRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{12}
}

func (m *CityPlacesRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityPlacesRequestPDB.Unmarshal(m, b)
}
func (m *CityPlacesRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityPlacesRequestPDB.Marshal(b, m, deterministic)
}
func (m *CityPlacesRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityPlacesRequestPDB.Merge(m, src)
}
func (m *CityPlacesRequestPDB) XXX_Size() int {
	return xxx_messageInfo_CityPlacesRequestPDB.Size(m)
}
func (m *CityPlacesRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityPlacesRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityPlacesRequestPDB proto.InternalMessageInfo

func (m *CityPlacesRequestPDB) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type CityPlacesResponsePDB struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Places               []*Place `protobuf:"bytes,4,rep,name=places,proto3" json:"places,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityPlacesResponsePDB) Reset()         { *m = CityPlacesResponsePDB{} }
func (m *CityPlacesResponsePDB) String() string { return proto.CompactTextString(m) }
func (*CityPlacesResponsePDB) ProtoMessage()    {}
func (*CityPlacesResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{13}
}

func (m *CityPlacesResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityPlacesResponsePDB.Unmarshal(m, b)
}
func (m *CityPlacesResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityPlacesResponsePDB.Marshal(b, m, deterministic)
}
func (m *CityPlacesResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityPlacesResponsePDB.Merge(m, src)
}
func (m *CityPlacesResponsePDB) XXX_Size() int {
	return xxx_messageInfo_CityPlacesResponsePDB.Size(m)
}
func (m *CityPlacesResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityPlacesResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityPlacesResponsePDB proto.InternalMessageInfo

func (m *CityPlacesResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CityPlacesResponsePDB) GetPlaces() []*Place {
	if m != nil {
		return m.Places
	}
	return nil
}

type VisitPlaceRequestPDB struct {
	UserEmail            string   `protobuf:"bytes,1,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	PlaceId              int32    `protobuf:"varint,2,opt,name=placeId,proto3" json:"placeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitPlaceRequestPDB) Reset()         { *m = VisitPlaceRequestPDB{} }
func (m *VisitPlaceRequestPDB) String() string { return proto.CompactTextString(m) }
func (*VisitPlaceRequestPDB) ProtoMessage()    {}
func (*VisitPlaceRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{14}
}

func (m *VisitPlaceRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitPlaceRequestPDB.Unmarshal(m, b)
}
func (m *VisitPlaceRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitPlaceRequestPDB.Marshal(b, m, deterministic)
}
func (m *VisitPlaceRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitPlaceRequestPDB.Merge(m, src)
}
func (m *VisitPlaceRequestPDB) XXX_Size() int {
	return xxx_messageInfo_VisitPlaceRequestPDB.Size(m)
}
func (m *VisitPlaceRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitPlaceRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitPlaceRequestPDB proto.InternalMessageInfo

func (m *VisitPlaceRequestPDB) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *VisitPlaceRequestPDB) GetPlaceId() int32 {
	if m != nil {
		return m.PlaceId
	}
	return 0
}

type VisitPlaceResponsePDB struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	TimeStamp            string   `protobuf:"bytes,2,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitPlaceResponsePDB) Reset()         { *m = VisitPlaceResponsePDB{} }
func (m *VisitPlaceResponsePDB) String() string { return proto.CompactTextString(m) }
func (*VisitPlaceResponsePDB) ProtoMessage()    {}
func (*VisitPlaceResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{15}
}

func (m *VisitPlaceResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitPlaceResponsePDB.Unmarshal(m, b)
}
func (m *VisitPlaceResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitPlaceResponsePDB.Marshal(b, m, deterministic)
}
func (m *VisitPlaceResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitPlaceResponsePDB.Merge(m, src)
}
func (m *VisitPlaceResponsePDB) XXX_Size() int {
	return xxx_messageInfo_VisitPlaceResponsePDB.Size(m)
}
func (m *VisitPlaceResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitPlaceResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitPlaceResponsePDB proto.InternalMessageInfo

func (m *VisitPlaceResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *VisitPlaceResponsePDB) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

type VisitedPlacesRequestPDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitedPlacesRequestPDB) Reset()         { *m = VisitedPlacesRequestPDB{} }
func (m *VisitedPlacesRequestPDB) String() string { return proto.CompactTextString(m) }
func (*VisitedPlacesRequestPDB) ProtoMessage()    {}
func (*VisitedPlacesRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{16}
}

func (m *VisitedPlacesRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitedPlacesRequestPDB.Unmarshal(m, b)
}
func (m *VisitedPlacesRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitedPlacesRequestPDB.Marshal(b, m, deterministic)
}
func (m *VisitedPlacesRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitedPlacesRequestPDB.Merge(m, src)
}
func (m *VisitedPlacesRequestPDB) XXX_Size() int {
	return xxx_messageInfo_VisitedPlacesRequestPDB.Size(m)
}
func (m *VisitedPlacesRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitedPlacesRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitedPlacesRequestPDB proto.InternalMessageInfo

func (m *VisitedPlacesRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type VisitedPlacesResponsePDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Places               []*Place `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitedPlacesResponsePDB) Reset()         { *m = VisitedPlacesResponsePDB{} }
func (m *VisitedPlacesResponsePDB) String() string { return proto.CompactTextString(m) }
func (*VisitedPlacesResponsePDB) ProtoMessage()    {}
func (*VisitedPlacesResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{17}
}

func (m *VisitedPlacesResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitedPlacesResponsePDB.Unmarshal(m, b)
}
func (m *VisitedPlacesResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitedPlacesResponsePDB.Marshal(b, m, deterministic)
}
func (m *VisitedPlacesResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitedPlacesResponsePDB.Merge(m, src)
}
func (m *VisitedPlacesResponsePDB) XXX_Size() int {
	return xxx_messageInfo_VisitedPlacesResponsePDB.Size(m)
}
func (m *VisitedPlacesResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitedPlacesResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitedPlacesResponsePDB proto.InternalMessageInfo

func (m *VisitedPlacesResponsePDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VisitedPlacesResponsePDB) GetPlaces() []*Place {
	if m != nil {
		return m.Places
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserResponsePDB)(nil), "wcity.CreateUserResponsePDB")
	proto.RegisterType((*GetUserRequestPDB)(nil), "wcity.GetUserRequestPDB")
	proto.RegisterType((*UserResponsePDB)(nil), "wcity.UserResponsePDB")
	proto.RegisterType((*CityRequestPDB)(nil), "wcity.CityRequestPDB")
	proto.RegisterType((*CityResponsePDB)(nil), "wcity.CityResponsePDB")
	proto.RegisterType((*PlaceRequestPDB)(nil), "wcity.PlaceRequestPDB")
	proto.RegisterType((*PlaceResponsePDB)(nil), "wcity.PlaceResponsePDB")
	proto.RegisterType((*UpdatedUserRequestPDB)(nil), "wcity.UpdatedUserRequestPDB")
	proto.RegisterType((*VisitedCitysRequestPDB)(nil), "wcity.VisitedCitysRequestPDB")
	proto.RegisterType((*VisitedCitysResponsePDB)(nil), "wcity.VisitedCitysResponsePDB")
	proto.RegisterType((*VisitCityRequestPDB)(nil), "wcity.VisitCityRequestPDB")
	proto.RegisterType((*VisitCityResponsePDB)(nil), "wcity.VisitCityResponsePDB")
	proto.RegisterType((*CityPlacesRequestPDB)(nil), "wcity.CityPlacesRequestPDB")
	proto.RegisterType((*CityPlacesResponsePDB)(nil), "wcity.CityPlacesResponsePDB")
	proto.RegisterType((*VisitPlaceRequestPDB)(nil), "wcity.VisitPlaceRequestPDB")
	proto.RegisterType((*VisitPlaceResponsePDB)(nil), "wcity.VisitPlaceResponsePDB")
	proto.RegisterType((*VisitedPlacesRequestPDB)(nil), "wcity.VisitedPlacesRequestPDB")
	proto.RegisterType((*VisitedPlacesResponsePDB)(nil), "wcity.VisitedPlacesResponsePDB")
}

func init() { proto.RegisterFile("profilesdb.proto", fileDescriptor_ff8a164433363f89) }

var fileDescriptor_ff8a164433363f89 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x4e, 0xdb, 0x4c,
	0x10, 0x56, 0x02, 0x01, 0x32, 0xf0, 0x13, 0xd8, 0x3f, 0x09, 0x91, 0x4b, 0x0b, 0xb5, 0x7a, 0xd1,
	0xde, 0xa4, 0x40, 0x55, 0xb5, 0x12, 0x12, 0x12, 0x81, 0x8a, 0x9e, 0x54, 0x59, 0x8e, 0xe0, 0xb6,
	0x32, 0xf6, 0xb6, 0x58, 0x72, 0x62, 0xd7, 0xeb, 0xb4, 0xe2, 0x75, 0xfa, 0x32, 0x7d, 0xad, 0xee,
	0xc9, 0xde, 0x5d, 0xc7, 0xa9, 0xe9, 0xe1, 0x2e, 0x3b, 0x33, 0xdf, 0x37, 0xdf, 0xce, 0xcc, 0x4e,
	0x0c, 0x5b, 0x49, 0x1a, 0x7f, 0x0a, 0x23, 0x4c, 0x82, 0xeb, 0x21, 0xfd, 0x99, 0xc5, 0xa8, 0xf5,
	0xcd, 0x0f, 0xb3, 0x5b, 0xab, 0x97, 0x3b, 0x3e, 0x92, 0x1b, 0x2f, 0xc5, 0x81, 0xf0, 0xda, 0x1f,
	0xa0, 0x77, 0x96, 0x62, 0x2f, 0xc3, 0x97, 0x04, 0xa7, 0x2e, 0x26, 0x49, 0x3c, 0x25, 0xd8, 0x39,
	0x1f, 0xa1, 0x2e, 0xb4, 0xbe, 0x7a, 0x51, 0x18, 0x0c, 0x1a, 0xfb, 0x8d, 0xc7, 0x6b, 0xae, 0x38,
	0xa0, 0x3d, 0x58, 0x9e, 0xd1, 0xc0, 0x41, 0x93, 0x1a, 0xd7, 0x8f, 0xd6, 0x87, 0x9c, 0x7b, 0xc8,
	0xb1, 0xdc, 0x61, 0x3f, 0x81, 0xed, 0x0b, 0x9c, 0x09, 0xb2, 0x2f, 0x33, 0x4c, 0x32, 0xc9, 0x85,
	0x27, 0x5e, 0x18, 0x71, 0x58, 0xdb, 0x15, 0x07, 0xfb, 0x35, 0x74, 0xfe, 0x51, 0xd2, 0x13, 0xd8,
	0x3c, 0xa3, 0x26, 0x2d, 0x23, 0x82, 0xe5, 0xa9, 0x37, 0xc1, 0x9c, 0xa7, 0xed, 0xf2, 0xdf, 0x68,
	0x00, 0xab, 0x7e, 0x3c, 0x9b, 0x66, 0xe9, 0xad, 0xd4, 0x91, 0x1f, 0x99, 0x12, 0x81, 0xbf, 0x83,
	0x12, 0x96, 0xbb, 0xa4, 0x84, 0x63, 0xb9, 0xc3, 0x1e, 0x43, 0xc7, 0x89, 0x3c, 0x1f, 0xd7, 0x48,
	0x41, 0x1a, 0x4f, 0x5b, 0x40, 0x75, 0x79, 0x4b, 0xa6, 0xbc, 0xf7, 0xb0, 0x25, 0x49, 0xeb, 0xf4,
	0xd9, 0xd0, 0x4a, 0x58, 0xa4, 0x14, 0xb8, 0x21, 0x05, 0x0a, 0xb4, 0x70, 0xd9, 0x3e, 0xf4, 0x2e,
	0x93, 0x80, 0x76, 0x3c, 0x58, 0xd4, 0xa5, 0x86, 0xd6, 0xa5, 0x42, 0x7e, 0x53, 0x93, 0xbf, 0x0f,
	0xeb, 0x01, 0x26, 0x7e, 0x1a, 0x26, 0x59, 0x18, 0x4f, 0xa5, 0x5c, 0xdd, 0x64, 0x0f, 0xa1, 0x7f,
	0x15, 0x92, 0x90, 0x26, 0x61, 0xc5, 0x21, 0x75, 0x59, 0x6c, 0x17, 0x76, 0xcc, 0x78, 0xe3, 0xa6,
	0x15, 0xb2, 0x1e, 0x42, 0x8b, 0x5d, 0x8d, 0x50, 0x5d, 0x4b, 0xe5, 0x56, 0x08, 0x8f, 0xfd, 0x0e,
	0xfe, 0xe7, 0x9c, 0xa5, 0xd1, 0xd8, 0x85, 0x36, 0x1b, 0x9a, 0x57, 0x1a, 0xa7, 0x32, 0xa0, 0x3e,
	0xac, 0x30, 0xf4, 0x9b, 0x80, 0x5f, 0xb8, 0xe5, 0xca, 0x93, 0xfd, 0x16, 0xba, 0x1a, 0x59, 0x5d,
	0x1f, 0x68, 0x8e, 0x2c, 0x9c, 0xe0, 0x71, 0xe6, 0x4d, 0x12, 0x59, 0x39, 0x65, 0xa0, 0xc5, 0xe9,
	0x32, 0x1a, 0xde, 0x15, 0xbd, 0x34, 0x2a, 0x77, 0xc3, 0xc8, 0x3d, 0xa6, 0x6f, 0x54, 0x8b, 0xaf,
	0x4b, 0xfe, 0x08, 0x56, 0x78, 0xa7, 0xc9, 0x60, 0x99, 0xd7, 0xc6, 0x9c, 0x02, 0xe9, 0xa3, 0x0f,
	0x5f, 0x5c, 0xa8, 0x3c, 0xae, 0xbf, 0x2e, 0x0f, 0x1d, 0x52, 0x8e, 0x2f, 0xea, 0x93, 0x1f, 0x69,
	0xb5, 0x7b, 0x3a, 0xdf, 0xdf, 0x55, 0xe8, 0x69, 0x31, 0x0e, 0x73, 0x45, 0xaa, 0x9e, 0x9f, 0x2b,
	0x18, 0x94, 0x00, 0x75, 0x03, 0xa4, 0xaa, 0xd4, 0x5c, 0x5c, 0xa5, 0xa3, 0x1f, 0x6b, 0x00, 0x8e,
	0x5c, 0x9c, 0x94, 0xea, 0x14, 0x36, 0xc6, 0xd8, 0x4b, 0xfd, 0x9b, 0xd3, 0x28, 0x3a, 0x1f, 0x9d,
	0xa2, 0x1d, 0x09, 0x2a, 0x8c, 0x52, 0xa8, 0xd5, 0x9f, 0x77, 0x90, 0x59, 0x94, 0x1d, 0x34, 0xd0,
	0x73, 0xd8, 0xa4, 0x0b, 0x92, 0x5a, 0xf8, 0xa0, 0x33, 0x92, 0xae, 0x8c, 0x15, 0xe6, 0x9c, 0x41,
	0x9f, 0x68, 0x0a, 0x7b, 0x01, 0x1d, 0xe1, 0x17, 0xf7, 0x5b, 0x8c, 0x33, 0xee, 0xc1, 0x81, 0xa0,
	0x16, 0x3c, 0xd2, 0x97, 0xa7, 0xb5, 0x9b, 0xa7, 0xa8, 0xfc, 0x03, 0x38, 0x81, 0x6d, 0xb1, 0x27,
	0xb4, 0x35, 0xf1, 0x3b, 0xf8, 0x63, 0x58, 0x95, 0xff, 0x04, 0x68, 0xa0, 0x94, 0x9a, 0x3b, 0xa7,
	0xa8, 0x53, 0x19, 0x7c, 0x98, 0xab, 0x66, 0xd7, 0x47, 0x7a, 0x2d, 0x0a, 0x48, 0xf9, 0x25, 0xbe,
	0xcc, 0xf5, 0x6a, 0xef, 0xfd, 0xae, 0x48, 0xa6, 0x94, 0x67, 0xea, 0x19, 0x21, 0x73, 0x32, 0xcb,
	0xc8, 0x63, 0x40, 0x42, 0xa6, 0xfe, 0x8a, 0x90, 0xd1, 0x02, 0x6b, 0xc7, 0x18, 0x2c, 0x13, 0x2c,
	0x04, 0xff, 0x09, 0xf8, 0x00, 0xd6, 0xa8, 0x66, 0x6e, 0x46, 0x7d, 0x33, 0xa8, 0x50, 0x6d, 0x50,
	0xa1, 0x73, 0x68, 0x17, 0x1b, 0x0c, 0x59, 0xd2, 0x55, 0xb1, 0x20, 0xad, 0x7b, 0xf3, 0x3e, 0x95,
	0xf7, 0x02, 0x40, 0x3d, 0x73, 0x64, 0x84, 0x96, 0xd3, 0xef, 0x56, 0x38, 0x15, 0x91, 0xc3, 0x07,
	0x5a, 0x5f, 0xfa, 0xe8, 0xbe, 0x0e, 0x98, 0xfb, 0xe7, 0xb0, 0x1e, 0x54, 0xba, 0x15, 0xe3, 0x18,
	0xb6, 0x14, 0xa3, 0x78, 0x26, 0xa8, 0x84, 0x29, 0x6f, 0x13, 0x6b, 0xaf, 0xda, 0xaf, 0xdf, 0xf7,
	0x3f, 0x39, 0x1b, 0x92, 0x71, 0xc1, 0x84, 0xd4, 0x11, 0x8d, 0x0e, 0xa1, 0x1f, 0xc6, 0xc3, 0xcf,
	0x69, 0xe2, 0xcb, 0xc8, 0xfc, 0x7b, 0x6c, 0xd4, 0x51, 0x0b, 0xc6, 0x61, 0xdf, 0x64, 0x4e, 0xe3,
	0x7b, 0x73, 0xc9, 0x75, 0xce, 0xae, 0x57, 0xf8, 0x27, 0xda, 0xb3, 0x9f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x6f, 0xc0, 0x79, 0xd2, 0xd4, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfilesDBClient is the client API for ProfilesDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfilesDBClient interface {
	SearchAllDBA(ctx context.Context, in *SearchAllRequest, opts ...grpc.CallOption) (ProfilesDB_SearchAllDBAClient, error)
	GetAllCitysDBA(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (ProfilesDB_GetAllCitysDBAClient, error)
	GetAllPlacesDBA(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (ProfilesDB_GetAllPlacesDBAClient, error)
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateUserResponsePDB, error)
	UpdateUserRequest(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateUserResponsePDB, error)
	GetUser(ctx context.Context, in *GetUserRequestPDB, opts ...grpc.CallOption) (*UserResponsePDB, error)
	CreateCity(ctx context.Context, in *City, opts ...grpc.CallOption) (*CityResponsePDB, error)
	UpdateCityRequest(ctx context.Context, in *City, opts ...grpc.CallOption) (*CityResponsePDB, error)
	GetCity(ctx context.Context, in *CityRequestPDB, opts ...grpc.CallOption) (*CityResponsePDB, error)
	CreatePlaceRequest(ctx context.Context, in *Place, opts ...grpc.CallOption) (*PlaceResponsePDB, error)
	UpdatePlaceRequest(ctx context.Context, in *Place, opts ...grpc.CallOption) (*PlaceResponsePDB, error)
	GetPlace(ctx context.Context, in *PlaceRequestPDB, opts ...grpc.CallOption) (*Place, error)
	VisitCity(ctx context.Context, in *VisitCityRequestPDB, opts ...grpc.CallOption) (*VisitCityResponsePDB, error)
	VisitPlace(ctx context.Context, in *VisitPlaceRequestPDB, opts ...grpc.CallOption) (*VisitPlaceResponsePDB, error)
	GetVisitedCitys(ctx context.Context, in *VisitedCitysRequestPDB, opts ...grpc.CallOption) (*VisitedCitysResponsePDB, error)
	GetVisitedPlaces(ctx context.Context, in *VisitedPlacesRequestPDB, opts ...grpc.CallOption) (*VisitedPlacesResponsePDB, error)
	GetCityPlaces(ctx context.Context, in *CityRequestPDB, opts ...grpc.CallOption) (*VisitedPlacesResponsePDB, error)
}

type profilesDBClient struct {
	cc *grpc.ClientConn
}

func NewProfilesDBClient(cc *grpc.ClientConn) ProfilesDBClient {
	return &profilesDBClient{cc}
}

func (c *profilesDBClient) SearchAllDBA(ctx context.Context, in *SearchAllRequest, opts ...grpc.CallOption) (ProfilesDB_SearchAllDBAClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfilesDB_serviceDesc.Streams[0], "/wcity.ProfilesDB/SearchAllDBA", opts...)
	if err != nil {
		return nil, err
	}
	x := &profilesDBSearchAllDBAClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfilesDB_SearchAllDBAClient interface {
	Recv() (*SearchAllResult, error)
	grpc.ClientStream
}

type profilesDBSearchAllDBAClient struct {
	grpc.ClientStream
}

func (x *profilesDBSearchAllDBAClient) Recv() (*SearchAllResult, error) {
	m := new(SearchAllResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profilesDBClient) GetAllCitysDBA(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (ProfilesDB_GetAllCitysDBAClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfilesDB_serviceDesc.Streams[1], "/wcity.ProfilesDB/GetAllCitysDBA", opts...)
	if err != nil {
		return nil, err
	}
	x := &profilesDBGetAllCitysDBAClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfilesDB_GetAllCitysDBAClient interface {
	Recv() (*City, error)
	grpc.ClientStream
}

type profilesDBGetAllCitysDBAClient struct {
	grpc.ClientStream
}

func (x *profilesDBGetAllCitysDBAClient) Recv() (*City, error) {
	m := new(City)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profilesDBClient) GetAllPlacesDBA(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (ProfilesDB_GetAllPlacesDBAClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfilesDB_serviceDesc.Streams[2], "/wcity.ProfilesDB/GetAllPlacesDBA", opts...)
	if err != nil {
		return nil, err
	}
	x := &profilesDBGetAllPlacesDBAClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfilesDB_GetAllPlacesDBAClient interface {
	Recv() (*Place, error)
	grpc.ClientStream
}

type profilesDBGetAllPlacesDBAClient struct {
	grpc.ClientStream
}

func (x *profilesDBGetAllPlacesDBAClient) Recv() (*Place, error) {
	m := new(Place)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profilesDBClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateUserResponsePDB, error) {
	out := new(CreateUserResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) UpdateUserRequest(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateUserResponsePDB, error) {
	out := new(CreateUserResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/UpdateUserRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetUser(ctx context.Context, in *GetUserRequestPDB, opts ...grpc.CallOption) (*UserResponsePDB, error) {
	out := new(UserResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) CreateCity(ctx context.Context, in *City, opts ...grpc.CallOption) (*CityResponsePDB, error) {
	out := new(CityResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/CreateCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) UpdateCityRequest(ctx context.Context, in *City, opts ...grpc.CallOption) (*CityResponsePDB, error) {
	out := new(CityResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/UpdateCityRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetCity(ctx context.Context, in *CityRequestPDB, opts ...grpc.CallOption) (*CityResponsePDB, error) {
	out := new(CityResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) CreatePlaceRequest(ctx context.Context, in *Place, opts ...grpc.CallOption) (*PlaceResponsePDB, error) {
	out := new(PlaceResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/CreatePlaceRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) UpdatePlaceRequest(ctx context.Context, in *Place, opts ...grpc.CallOption) (*PlaceResponsePDB, error) {
	out := new(PlaceResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/UpdatePlaceRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetPlace(ctx context.Context, in *PlaceRequestPDB, opts ...grpc.CallOption) (*Place, error) {
	out := new(Place)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) VisitCity(ctx context.Context, in *VisitCityRequestPDB, opts ...grpc.CallOption) (*VisitCityResponsePDB, error) {
	out := new(VisitCityResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/VisitCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) VisitPlace(ctx context.Context, in *VisitPlaceRequestPDB, opts ...grpc.CallOption) (*VisitPlaceResponsePDB, error) {
	out := new(VisitPlaceResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/VisitPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetVisitedCitys(ctx context.Context, in *VisitedCitysRequestPDB, opts ...grpc.CallOption) (*VisitedCitysResponsePDB, error) {
	out := new(VisitedCitysResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetVisitedCitys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetVisitedPlaces(ctx context.Context, in *VisitedPlacesRequestPDB, opts ...grpc.CallOption) (*VisitedPlacesResponsePDB, error) {
	out := new(VisitedPlacesResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetVisitedPlaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetCityPlaces(ctx context.Context, in *CityRequestPDB, opts ...grpc.CallOption) (*VisitedPlacesResponsePDB, error) {
	out := new(VisitedPlacesResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetCityPlaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilesDBServer is the server API for ProfilesDB service.
type ProfilesDBServer interface {
	SearchAllDBA(*SearchAllRequest, ProfilesDB_SearchAllDBAServer) error
	GetAllCitysDBA(*GetAllRequest, ProfilesDB_GetAllCitysDBAServer) error
	GetAllPlacesDBA(*GetAllRequest, ProfilesDB_GetAllPlacesDBAServer) error
	CreateUser(context.Context, *User) (*CreateUserResponsePDB, error)
	UpdateUserRequest(context.Context, *User) (*CreateUserResponsePDB, error)
	GetUser(context.Context, *GetUserRequestPDB) (*UserResponsePDB, error)
	CreateCity(context.Context, *City) (*CityResponsePDB, error)
	UpdateCityRequest(context.Context, *City) (*CityResponsePDB, error)
	GetCity(context.Context, *CityRequestPDB) (*CityResponsePDB, error)
	CreatePlaceRequest(context.Context, *Place) (*PlaceResponsePDB, error)
	UpdatePlaceRequest(context.Context, *Place) (*PlaceResponsePDB, error)
	GetPlace(context.Context, *PlaceRequestPDB) (*Place, error)
	VisitCity(context.Context, *VisitCityRequestPDB) (*VisitCityResponsePDB, error)
	VisitPlace(context.Context, *VisitPlaceRequestPDB) (*VisitPlaceResponsePDB, error)
	GetVisitedCitys(context.Context, *VisitedCitysRequestPDB) (*VisitedCitysResponsePDB, error)
	GetVisitedPlaces(context.Context, *VisitedPlacesRequestPDB) (*VisitedPlacesResponsePDB, error)
	GetCityPlaces(context.Context, *CityRequestPDB) (*VisitedPlacesResponsePDB, error)
}

// UnimplementedProfilesDBServer can be embedded to have forward compatible implementations.
type UnimplementedProfilesDBServer struct {
}

func (*UnimplementedProfilesDBServer) SearchAllDBA(req *SearchAllRequest, srv ProfilesDB_SearchAllDBAServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchAllDBA not implemented")
}
func (*UnimplementedProfilesDBServer) GetAllCitysDBA(req *GetAllRequest, srv ProfilesDB_GetAllCitysDBAServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllCitysDBA not implemented")
}
func (*UnimplementedProfilesDBServer) GetAllPlacesDBA(req *GetAllRequest, srv ProfilesDB_GetAllPlacesDBAServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllPlacesDBA not implemented")
}
func (*UnimplementedProfilesDBServer) CreateUser(ctx context.Context, req *User) (*CreateUserResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedProfilesDBServer) UpdateUserRequest(ctx context.Context, req *User) (*CreateUserResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserRequest not implemented")
}
func (*UnimplementedProfilesDBServer) GetUser(ctx context.Context, req *GetUserRequestPDB) (*UserResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedProfilesDBServer) CreateCity(ctx context.Context, req *City) (*CityResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCity not implemented")
}
func (*UnimplementedProfilesDBServer) UpdateCityRequest(ctx context.Context, req *City) (*CityResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCityRequest not implemented")
}
func (*UnimplementedProfilesDBServer) GetCity(ctx context.Context, req *CityRequestPDB) (*CityResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCity not implemented")
}
func (*UnimplementedProfilesDBServer) CreatePlaceRequest(ctx context.Context, req *Place) (*PlaceResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlaceRequest not implemented")
}
func (*UnimplementedProfilesDBServer) UpdatePlaceRequest(ctx context.Context, req *Place) (*PlaceResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlaceRequest not implemented")
}
func (*UnimplementedProfilesDBServer) GetPlace(ctx context.Context, req *PlaceRequestPDB) (*Place, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlace not implemented")
}
func (*UnimplementedProfilesDBServer) VisitCity(ctx context.Context, req *VisitCityRequestPDB) (*VisitCityResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitCity not implemented")
}
func (*UnimplementedProfilesDBServer) VisitPlace(ctx context.Context, req *VisitPlaceRequestPDB) (*VisitPlaceResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitPlace not implemented")
}
func (*UnimplementedProfilesDBServer) GetVisitedCitys(ctx context.Context, req *VisitedCitysRequestPDB) (*VisitedCitysResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitedCitys not implemented")
}
func (*UnimplementedProfilesDBServer) GetVisitedPlaces(ctx context.Context, req *VisitedPlacesRequestPDB) (*VisitedPlacesResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitedPlaces not implemented")
}
func (*UnimplementedProfilesDBServer) GetCityPlaces(ctx context.Context, req *CityRequestPDB) (*VisitedPlacesResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCityPlaces not implemented")
}

func RegisterProfilesDBServer(s *grpc.Server, srv ProfilesDBServer) {
	s.RegisterService(&_ProfilesDB_serviceDesc, srv)
}

func _ProfilesDB_SearchAllDBA_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfilesDBServer).SearchAllDBA(m, &profilesDBSearchAllDBAServer{stream})
}

type ProfilesDB_SearchAllDBAServer interface {
	Send(*SearchAllResult) error
	grpc.ServerStream
}

type profilesDBSearchAllDBAServer struct {
	grpc.ServerStream
}

func (x *profilesDBSearchAllDBAServer) Send(m *SearchAllResult) error {
	return x.ServerStream.SendMsg(m)
}

func _ProfilesDB_GetAllCitysDBA_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfilesDBServer).GetAllCitysDBA(m, &profilesDBGetAllCitysDBAServer{stream})
}

type ProfilesDB_GetAllCitysDBAServer interface {
	Send(*City) error
	grpc.ServerStream
}

type profilesDBGetAllCitysDBAServer struct {
	grpc.ServerStream
}

func (x *profilesDBGetAllCitysDBAServer) Send(m *City) error {
	return x.ServerStream.SendMsg(m)
}

func _ProfilesDB_GetAllPlacesDBA_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfilesDBServer).GetAllPlacesDBA(m, &profilesDBGetAllPlacesDBAServer{stream})
}

type ProfilesDB_GetAllPlacesDBAServer interface {
	Send(*Place) error
	grpc.ServerStream
}

type profilesDBGetAllPlacesDBAServer struct {
	grpc.ServerStream
}

func (x *profilesDBGetAllPlacesDBAServer) Send(m *Place) error {
	return x.ServerStream.SendMsg(m)
}

func _ProfilesDB_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_UpdateUserRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).UpdateUserRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/UpdateUserRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).UpdateUserRequest(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetUser(ctx, req.(*GetUserRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_CreateCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(City)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).CreateCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/CreateCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).CreateCity(ctx, req.(*City))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_UpdateCityRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(City)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).UpdateCityRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/UpdateCityRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).UpdateCityRequest(ctx, req.(*City))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetCity(ctx, req.(*CityRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_CreatePlaceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Place)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).CreatePlaceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/CreatePlaceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).CreatePlaceRequest(ctx, req.(*Place))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_UpdatePlaceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Place)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).UpdatePlaceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/UpdatePlaceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).UpdatePlaceRequest(ctx, req.(*Place))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetPlace(ctx, req.(*PlaceRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_VisitCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitCityRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).VisitCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/VisitCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).VisitCity(ctx, req.(*VisitCityRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_VisitPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitPlaceRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).VisitPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/VisitPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).VisitPlace(ctx, req.(*VisitPlaceRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetVisitedCitys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitedCitysRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetVisitedCitys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetVisitedCitys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetVisitedCitys(ctx, req.(*VisitedCitysRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetVisitedPlaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitedPlacesRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetVisitedPlaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetVisitedPlaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetVisitedPlaces(ctx, req.(*VisitedPlacesRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetCityPlaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetCityPlaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetCityPlaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetCityPlaces(ctx, req.(*CityRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfilesDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wcity.ProfilesDB",
	HandlerType: (*ProfilesDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _ProfilesDB_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUserRequest",
			Handler:    _ProfilesDB_UpdateUserRequest_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _ProfilesDB_GetUser_Handler,
		},
		{
			MethodName: "CreateCity",
			Handler:    _ProfilesDB_CreateCity_Handler,
		},
		{
			MethodName: "UpdateCityRequest",
			Handler:    _ProfilesDB_UpdateCityRequest_Handler,
		},
		{
			MethodName: "GetCity",
			Handler:    _ProfilesDB_GetCity_Handler,
		},
		{
			MethodName: "CreatePlaceRequest",
			Handler:    _ProfilesDB_CreatePlaceRequest_Handler,
		},
		{
			MethodName: "UpdatePlaceRequest",
			Handler:    _ProfilesDB_UpdatePlaceRequest_Handler,
		},
		{
			MethodName: "GetPlace",
			Handler:    _ProfilesDB_GetPlace_Handler,
		},
		{
			MethodName: "VisitCity",
			Handler:    _ProfilesDB_VisitCity_Handler,
		},
		{
			MethodName: "VisitPlace",
			Handler:    _ProfilesDB_VisitPlace_Handler,
		},
		{
			MethodName: "GetVisitedCitys",
			Handler:    _ProfilesDB_GetVisitedCitys_Handler,
		},
		{
			MethodName: "GetVisitedPlaces",
			Handler:    _ProfilesDB_GetVisitedPlaces_Handler,
		},
		{
			MethodName: "GetCityPlaces",
			Handler:    _ProfilesDB_GetCityPlaces_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchAllDBA",
			Handler:       _ProfilesDB_SearchAllDBA_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllCitysDBA",
			Handler:       _ProfilesDB_GetAllCitysDBA_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAllPlacesDBA",
			Handler:       _ProfilesDB_GetAllPlacesDBA_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "profilesdb.proto",
}
