// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profilesdb.proto

package wcity

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequestPDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequestPDB) Reset()         { *m = CreateUserRequestPDB{} }
func (m *CreateUserRequestPDB) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequestPDB) ProtoMessage()    {}
func (*CreateUserRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{0}
}

func (m *CreateUserRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequestPDB.Unmarshal(m, b)
}
func (m *CreateUserRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequestPDB.Marshal(b, m, deterministic)
}
func (m *CreateUserRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequestPDB.Merge(m, src)
}
func (m *CreateUserRequestPDB) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequestPDB.Size(m)
}
func (m *CreateUserRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequestPDB proto.InternalMessageInfo

func (m *CreateUserRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequestPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequestPDB) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateUserResponsePDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Valied               string   `protobuf:"bytes,2,opt,name=valied,proto3" json:"valied,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponsePDB) Reset()         { *m = CreateUserResponsePDB{} }
func (m *CreateUserResponsePDB) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponsePDB) ProtoMessage()    {}
func (*CreateUserResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{1}
}

func (m *CreateUserResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponsePDB.Unmarshal(m, b)
}
func (m *CreateUserResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponsePDB.Marshal(b, m, deterministic)
}
func (m *CreateUserResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponsePDB.Merge(m, src)
}
func (m *CreateUserResponsePDB) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponsePDB.Size(m)
}
func (m *CreateUserResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponsePDB proto.InternalMessageInfo

func (m *CreateUserResponsePDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserResponsePDB) GetValied() string {
	if m != nil {
		return m.Valied
	}
	return ""
}

type GetUserRequestPDB struct {
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequestPDB) Reset()         { *m = GetUserRequestPDB{} }
func (m *GetUserRequestPDB) String() string { return proto.CompactTextString(m) }
func (*GetUserRequestPDB) ProtoMessage()    {}
func (*GetUserRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{2}
}

func (m *GetUserRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequestPDB.Unmarshal(m, b)
}
func (m *GetUserRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequestPDB.Marshal(b, m, deterministic)
}
func (m *GetUserRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequestPDB.Merge(m, src)
}
func (m *GetUserRequestPDB) XXX_Size() int {
	return xxx_messageInfo_GetUserRequestPDB.Size(m)
}
func (m *GetUserRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequestPDB proto.InternalMessageInfo

func (m *GetUserRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserResponsePDB struct {
	Email                string         `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string         `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VisitedCitys         []*CityMinPDB  `protobuf:"bytes,4,rep,name=visitedCitys,proto3" json:"visitedCitys,omitempty"`
	VisitedPlaces        []*PlaceMinPDB `protobuf:"bytes,5,rep,name=visitedPlaces,proto3" json:"visitedPlaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserResponsePDB) Reset()         { *m = UserResponsePDB{} }
func (m *UserResponsePDB) String() string { return proto.CompactTextString(m) }
func (*UserResponsePDB) ProtoMessage()    {}
func (*UserResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{3}
}

func (m *UserResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponsePDB.Unmarshal(m, b)
}
func (m *UserResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponsePDB.Marshal(b, m, deterministic)
}
func (m *UserResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponsePDB.Merge(m, src)
}
func (m *UserResponsePDB) XXX_Size() int {
	return xxx_messageInfo_UserResponsePDB.Size(m)
}
func (m *UserResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponsePDB proto.InternalMessageInfo

func (m *UserResponsePDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponsePDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponsePDB) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UserResponsePDB) GetVisitedCitys() []*CityMinPDB {
	if m != nil {
		return m.VisitedCitys
	}
	return nil
}

func (m *UserResponsePDB) GetVisitedPlaces() []*PlaceMinPDB {
	if m != nil {
		return m.VisitedPlaces
	}
	return nil
}

type CityMinPDB struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	CreatorEmail         string   `protobuf:"bytes,3,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityMinPDB) Reset()         { *m = CityMinPDB{} }
func (m *CityMinPDB) String() string { return proto.CompactTextString(m) }
func (*CityMinPDB) ProtoMessage()    {}
func (*CityMinPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{4}
}

func (m *CityMinPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityMinPDB.Unmarshal(m, b)
}
func (m *CityMinPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityMinPDB.Marshal(b, m, deterministic)
}
func (m *CityMinPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityMinPDB.Merge(m, src)
}
func (m *CityMinPDB) XXX_Size() int {
	return xxx_messageInfo_CityMinPDB.Size(m)
}
func (m *CityMinPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityMinPDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityMinPDB proto.InternalMessageInfo

func (m *CityMinPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CityMinPDB) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CityMinPDB) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

type CityPDB struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country              string          `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	CreatorEmail         string          `protobuf:"bytes,3,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	Location             *GeolocationPDB `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Description          string          `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Places               []*PlaceMinPDB  `protobuf:"bytes,6,rep,name=places,proto3" json:"places,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CityPDB) Reset()         { *m = CityPDB{} }
func (m *CityPDB) String() string { return proto.CompactTextString(m) }
func (*CityPDB) ProtoMessage()    {}
func (*CityPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{5}
}

func (m *CityPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityPDB.Unmarshal(m, b)
}
func (m *CityPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityPDB.Marshal(b, m, deterministic)
}
func (m *CityPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityPDB.Merge(m, src)
}
func (m *CityPDB) XXX_Size() int {
	return xxx_messageInfo_CityPDB.Size(m)
}
func (m *CityPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityPDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityPDB proto.InternalMessageInfo

func (m *CityPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CityPDB) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CityPDB) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

func (m *CityPDB) GetLocation() *GeolocationPDB {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *CityPDB) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CityPDB) GetPlaces() []*PlaceMinPDB {
	if m != nil {
		return m.Places
	}
	return nil
}

type CityRequestPDB struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityRequestPDB) Reset()         { *m = CityRequestPDB{} }
func (m *CityRequestPDB) String() string { return proto.CompactTextString(m) }
func (*CityRequestPDB) ProtoMessage()    {}
func (*CityRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{6}
}

func (m *CityRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityRequestPDB.Unmarshal(m, b)
}
func (m *CityRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityRequestPDB.Marshal(b, m, deterministic)
}
func (m *CityRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityRequestPDB.Merge(m, src)
}
func (m *CityRequestPDB) XXX_Size() int {
	return xxx_messageInfo_CityRequestPDB.Size(m)
}
func (m *CityRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityRequestPDB proto.InternalMessageInfo

func (m *CityRequestPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CityRequestPDB) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type CityResponsePDB struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Valid                bool     `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	City                 *CityPDB `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityResponsePDB) Reset()         { *m = CityResponsePDB{} }
func (m *CityResponsePDB) String() string { return proto.CompactTextString(m) }
func (*CityResponsePDB) ProtoMessage()    {}
func (*CityResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{7}
}

func (m *CityResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityResponsePDB.Unmarshal(m, b)
}
func (m *CityResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityResponsePDB.Marshal(b, m, deterministic)
}
func (m *CityResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityResponsePDB.Merge(m, src)
}
func (m *CityResponsePDB) XXX_Size() int {
	return xxx_messageInfo_CityResponsePDB.Size(m)
}
func (m *CityResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityResponsePDB proto.InternalMessageInfo

func (m *CityResponsePDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CityResponsePDB) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CityResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CityResponsePDB) GetCity() *CityPDB {
	if m != nil {
		return m.City
	}
	return nil
}

type GeolocationPDB struct {
	Lon                  float32  `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeolocationPDB) Reset()         { *m = GeolocationPDB{} }
func (m *GeolocationPDB) String() string { return proto.CompactTextString(m) }
func (*GeolocationPDB) ProtoMessage()    {}
func (*GeolocationPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{8}
}

func (m *GeolocationPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeolocationPDB.Unmarshal(m, b)
}
func (m *GeolocationPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeolocationPDB.Marshal(b, m, deterministic)
}
func (m *GeolocationPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeolocationPDB.Merge(m, src)
}
func (m *GeolocationPDB) XXX_Size() int {
	return xxx_messageInfo_GeolocationPDB.Size(m)
}
func (m *GeolocationPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_GeolocationPDB.DiscardUnknown(m)
}

var xxx_messageInfo_GeolocationPDB proto.InternalMessageInfo

func (m *GeolocationPDB) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *GeolocationPDB) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type PlaceMinPDB struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CityID               string   `protobuf:"bytes,2,opt,name=cityID,proto3" json:"cityID,omitempty"`
	CreatorEmail         string   `protobuf:"bytes,3,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceMinPDB) Reset()         { *m = PlaceMinPDB{} }
func (m *PlaceMinPDB) String() string { return proto.CompactTextString(m) }
func (*PlaceMinPDB) ProtoMessage()    {}
func (*PlaceMinPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{9}
}

func (m *PlaceMinPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceMinPDB.Unmarshal(m, b)
}
func (m *PlaceMinPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceMinPDB.Marshal(b, m, deterministic)
}
func (m *PlaceMinPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceMinPDB.Merge(m, src)
}
func (m *PlaceMinPDB) XXX_Size() int {
	return xxx_messageInfo_PlaceMinPDB.Size(m)
}
func (m *PlaceMinPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceMinPDB.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceMinPDB proto.InternalMessageInfo

func (m *PlaceMinPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaceMinPDB) GetCityID() string {
	if m != nil {
		return m.CityID
	}
	return ""
}

func (m *PlaceMinPDB) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

type PlacePDB struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CityID               string          `protobuf:"bytes,2,opt,name=cityID,proto3" json:"cityID,omitempty"`
	CreatorEmail         string          `protobuf:"bytes,3,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	Location             *GeolocationPDB `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Description          string          `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PlacePDB) Reset()         { *m = PlacePDB{} }
func (m *PlacePDB) String() string { return proto.CompactTextString(m) }
func (*PlacePDB) ProtoMessage()    {}
func (*PlacePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{10}
}

func (m *PlacePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacePDB.Unmarshal(m, b)
}
func (m *PlacePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacePDB.Marshal(b, m, deterministic)
}
func (m *PlacePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacePDB.Merge(m, src)
}
func (m *PlacePDB) XXX_Size() int {
	return xxx_messageInfo_PlacePDB.Size(m)
}
func (m *PlacePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacePDB.DiscardUnknown(m)
}

var xxx_messageInfo_PlacePDB proto.InternalMessageInfo

func (m *PlacePDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlacePDB) GetCityID() string {
	if m != nil {
		return m.CityID
	}
	return ""
}

func (m *PlacePDB) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

func (m *PlacePDB) GetLocation() *GeolocationPDB {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *PlacePDB) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type PlaceRequestPDB struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CityID               string   `protobuf:"bytes,2,opt,name=cityID,proto3" json:"cityID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceRequestPDB) Reset()         { *m = PlaceRequestPDB{} }
func (m *PlaceRequestPDB) String() string { return proto.CompactTextString(m) }
func (*PlaceRequestPDB) ProtoMessage()    {}
func (*PlaceRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{11}
}

func (m *PlaceRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceRequestPDB.Unmarshal(m, b)
}
func (m *PlaceRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceRequestPDB.Marshal(b, m, deterministic)
}
func (m *PlaceRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceRequestPDB.Merge(m, src)
}
func (m *PlaceRequestPDB) XXX_Size() int {
	return xxx_messageInfo_PlaceRequestPDB.Size(m)
}
func (m *PlaceRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceRequestPDB proto.InternalMessageInfo

func (m *PlaceRequestPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaceRequestPDB) GetCityID() string {
	if m != nil {
		return m.CityID
	}
	return ""
}

type PlaceResponsePDB struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CityID               string    `protobuf:"bytes,2,opt,name=cityID,proto3" json:"cityID,omitempty"`
	Valid                bool      `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	Place                *PlacePDB `protobuf:"bytes,4,opt,name=place,proto3" json:"place,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlaceResponsePDB) Reset()         { *m = PlaceResponsePDB{} }
func (m *PlaceResponsePDB) String() string { return proto.CompactTextString(m) }
func (*PlaceResponsePDB) ProtoMessage()    {}
func (*PlaceResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{12}
}

func (m *PlaceResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceResponsePDB.Unmarshal(m, b)
}
func (m *PlaceResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceResponsePDB.Marshal(b, m, deterministic)
}
func (m *PlaceResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceResponsePDB.Merge(m, src)
}
func (m *PlaceResponsePDB) XXX_Size() int {
	return xxx_messageInfo_PlaceResponsePDB.Size(m)
}
func (m *PlaceResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceResponsePDB proto.InternalMessageInfo

func (m *PlaceResponsePDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaceResponsePDB) GetCityID() string {
	if m != nil {
		return m.CityID
	}
	return ""
}

func (m *PlaceResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *PlaceResponsePDB) GetPlace() *PlacePDB {
	if m != nil {
		return m.Place
	}
	return nil
}

type UpdatedUserRequestPDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatedUserRequestPDB) Reset()         { *m = UpdatedUserRequestPDB{} }
func (m *UpdatedUserRequestPDB) String() string { return proto.CompactTextString(m) }
func (*UpdatedUserRequestPDB) ProtoMessage()    {}
func (*UpdatedUserRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{13}
}

func (m *UpdatedUserRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatedUserRequestPDB.Unmarshal(m, b)
}
func (m *UpdatedUserRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatedUserRequestPDB.Marshal(b, m, deterministic)
}
func (m *UpdatedUserRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatedUserRequestPDB.Merge(m, src)
}
func (m *UpdatedUserRequestPDB) XXX_Size() int {
	return xxx_messageInfo_UpdatedUserRequestPDB.Size(m)
}
func (m *UpdatedUserRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatedUserRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatedUserRequestPDB proto.InternalMessageInfo

func (m *UpdatedUserRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdatedUserRequestPDB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatedUserRequestPDB) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type VisitedCitysRequestPDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitedCitysRequestPDB) Reset()         { *m = VisitedCitysRequestPDB{} }
func (m *VisitedCitysRequestPDB) String() string { return proto.CompactTextString(m) }
func (*VisitedCitysRequestPDB) ProtoMessage()    {}
func (*VisitedCitysRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{14}
}

func (m *VisitedCitysRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitedCitysRequestPDB.Unmarshal(m, b)
}
func (m *VisitedCitysRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitedCitysRequestPDB.Marshal(b, m, deterministic)
}
func (m *VisitedCitysRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitedCitysRequestPDB.Merge(m, src)
}
func (m *VisitedCitysRequestPDB) XXX_Size() int {
	return xxx_messageInfo_VisitedCitysRequestPDB.Size(m)
}
func (m *VisitedCitysRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitedCitysRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitedCitysRequestPDB proto.InternalMessageInfo

func (m *VisitedCitysRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type VisitedCitysResponsePDB struct {
	Email                string     `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Citys                []*CityPDB `protobuf:"bytes,2,rep,name=citys,proto3" json:"citys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VisitedCitysResponsePDB) Reset()         { *m = VisitedCitysResponsePDB{} }
func (m *VisitedCitysResponsePDB) String() string { return proto.CompactTextString(m) }
func (*VisitedCitysResponsePDB) ProtoMessage()    {}
func (*VisitedCitysResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{15}
}

func (m *VisitedCitysResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitedCitysResponsePDB.Unmarshal(m, b)
}
func (m *VisitedCitysResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitedCitysResponsePDB.Marshal(b, m, deterministic)
}
func (m *VisitedCitysResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitedCitysResponsePDB.Merge(m, src)
}
func (m *VisitedCitysResponsePDB) XXX_Size() int {
	return xxx_messageInfo_VisitedCitysResponsePDB.Size(m)
}
func (m *VisitedCitysResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitedCitysResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitedCitysResponsePDB proto.InternalMessageInfo

func (m *VisitedCitysResponsePDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VisitedCitysResponsePDB) GetCitys() []*CityPDB {
	if m != nil {
		return m.Citys
	}
	return nil
}

type VisitCityRequestPDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CityName             string   `protobuf:"bytes,2,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CityCountry          string   `protobuf:"bytes,3,opt,name=cityCountry,proto3" json:"cityCountry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitCityRequestPDB) Reset()         { *m = VisitCityRequestPDB{} }
func (m *VisitCityRequestPDB) String() string { return proto.CompactTextString(m) }
func (*VisitCityRequestPDB) ProtoMessage()    {}
func (*VisitCityRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{16}
}

func (m *VisitCityRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitCityRequestPDB.Unmarshal(m, b)
}
func (m *VisitCityRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitCityRequestPDB.Marshal(b, m, deterministic)
}
func (m *VisitCityRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitCityRequestPDB.Merge(m, src)
}
func (m *VisitCityRequestPDB) XXX_Size() int {
	return xxx_messageInfo_VisitCityRequestPDB.Size(m)
}
func (m *VisitCityRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitCityRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitCityRequestPDB proto.InternalMessageInfo

func (m *VisitCityRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VisitCityRequestPDB) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *VisitCityRequestPDB) GetCityCountry() string {
	if m != nil {
		return m.CityCountry
	}
	return ""
}

type VisitCityResponsePDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CityName             string   `protobuf:"bytes,2,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CityCountry          string   `protobuf:"bytes,3,opt,name=cityCountry,proto3" json:"cityCountry,omitempty"`
	Valid                bool     `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitCityResponsePDB) Reset()         { *m = VisitCityResponsePDB{} }
func (m *VisitCityResponsePDB) String() string { return proto.CompactTextString(m) }
func (*VisitCityResponsePDB) ProtoMessage()    {}
func (*VisitCityResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{17}
}

func (m *VisitCityResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitCityResponsePDB.Unmarshal(m, b)
}
func (m *VisitCityResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitCityResponsePDB.Marshal(b, m, deterministic)
}
func (m *VisitCityResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitCityResponsePDB.Merge(m, src)
}
func (m *VisitCityResponsePDB) XXX_Size() int {
	return xxx_messageInfo_VisitCityResponsePDB.Size(m)
}
func (m *VisitCityResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitCityResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitCityResponsePDB proto.InternalMessageInfo

func (m *VisitCityResponsePDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VisitCityResponsePDB) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *VisitCityResponsePDB) GetCityCountry() string {
	if m != nil {
		return m.CityCountry
	}
	return ""
}

func (m *VisitCityResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type CityPlacesRequestPDB struct {
	CityName             string   `protobuf:"bytes,1,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CityCountry          string   `protobuf:"bytes,2,opt,name=cityCountry,proto3" json:"cityCountry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityPlacesRequestPDB) Reset()         { *m = CityPlacesRequestPDB{} }
func (m *CityPlacesRequestPDB) String() string { return proto.CompactTextString(m) }
func (*CityPlacesRequestPDB) ProtoMessage()    {}
func (*CityPlacesRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{18}
}

func (m *CityPlacesRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityPlacesRequestPDB.Unmarshal(m, b)
}
func (m *CityPlacesRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityPlacesRequestPDB.Marshal(b, m, deterministic)
}
func (m *CityPlacesRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityPlacesRequestPDB.Merge(m, src)
}
func (m *CityPlacesRequestPDB) XXX_Size() int {
	return xxx_messageInfo_CityPlacesRequestPDB.Size(m)
}
func (m *CityPlacesRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityPlacesRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityPlacesRequestPDB proto.InternalMessageInfo

func (m *CityPlacesRequestPDB) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *CityPlacesRequestPDB) GetCityCountry() string {
	if m != nil {
		return m.CityCountry
	}
	return ""
}

type CityPlacesResponsePDB struct {
	CityName             string      `protobuf:"bytes,1,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CityCountry          string      `protobuf:"bytes,2,opt,name=cityCountry,proto3" json:"cityCountry,omitempty"`
	Valid                bool        `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	Places               []*PlacePDB `protobuf:"bytes,4,rep,name=places,proto3" json:"places,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CityPlacesResponsePDB) Reset()         { *m = CityPlacesResponsePDB{} }
func (m *CityPlacesResponsePDB) String() string { return proto.CompactTextString(m) }
func (*CityPlacesResponsePDB) ProtoMessage()    {}
func (*CityPlacesResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{19}
}

func (m *CityPlacesResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityPlacesResponsePDB.Unmarshal(m, b)
}
func (m *CityPlacesResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityPlacesResponsePDB.Marshal(b, m, deterministic)
}
func (m *CityPlacesResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityPlacesResponsePDB.Merge(m, src)
}
func (m *CityPlacesResponsePDB) XXX_Size() int {
	return xxx_messageInfo_CityPlacesResponsePDB.Size(m)
}
func (m *CityPlacesResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_CityPlacesResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_CityPlacesResponsePDB proto.InternalMessageInfo

func (m *CityPlacesResponsePDB) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *CityPlacesResponsePDB) GetCityCountry() string {
	if m != nil {
		return m.CityCountry
	}
	return ""
}

func (m *CityPlacesResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CityPlacesResponsePDB) GetPlaces() []*PlacePDB {
	if m != nil {
		return m.Places
	}
	return nil
}

type VisitPlaceRequestPDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PlaceName            string   `protobuf:"bytes,2,opt,name=placeName,proto3" json:"placeName,omitempty"`
	PlaceCity            string   `protobuf:"bytes,3,opt,name=placeCity,proto3" json:"placeCity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitPlaceRequestPDB) Reset()         { *m = VisitPlaceRequestPDB{} }
func (m *VisitPlaceRequestPDB) String() string { return proto.CompactTextString(m) }
func (*VisitPlaceRequestPDB) ProtoMessage()    {}
func (*VisitPlaceRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{20}
}

func (m *VisitPlaceRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitPlaceRequestPDB.Unmarshal(m, b)
}
func (m *VisitPlaceRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitPlaceRequestPDB.Marshal(b, m, deterministic)
}
func (m *VisitPlaceRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitPlaceRequestPDB.Merge(m, src)
}
func (m *VisitPlaceRequestPDB) XXX_Size() int {
	return xxx_messageInfo_VisitPlaceRequestPDB.Size(m)
}
func (m *VisitPlaceRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitPlaceRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitPlaceRequestPDB proto.InternalMessageInfo

func (m *VisitPlaceRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VisitPlaceRequestPDB) GetPlaceName() string {
	if m != nil {
		return m.PlaceName
	}
	return ""
}

func (m *VisitPlaceRequestPDB) GetPlaceCity() string {
	if m != nil {
		return m.PlaceCity
	}
	return ""
}

type VisitPlaceResponsePDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PlaceName            string   `protobuf:"bytes,2,opt,name=placeName,proto3" json:"placeName,omitempty"`
	PlaceCity            string   `protobuf:"bytes,3,opt,name=placeCity,proto3" json:"placeCity,omitempty"`
	Valid                bool     `protobuf:"varint,4,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitPlaceResponsePDB) Reset()         { *m = VisitPlaceResponsePDB{} }
func (m *VisitPlaceResponsePDB) String() string { return proto.CompactTextString(m) }
func (*VisitPlaceResponsePDB) ProtoMessage()    {}
func (*VisitPlaceResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{21}
}

func (m *VisitPlaceResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitPlaceResponsePDB.Unmarshal(m, b)
}
func (m *VisitPlaceResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitPlaceResponsePDB.Marshal(b, m, deterministic)
}
func (m *VisitPlaceResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitPlaceResponsePDB.Merge(m, src)
}
func (m *VisitPlaceResponsePDB) XXX_Size() int {
	return xxx_messageInfo_VisitPlaceResponsePDB.Size(m)
}
func (m *VisitPlaceResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitPlaceResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitPlaceResponsePDB proto.InternalMessageInfo

func (m *VisitPlaceResponsePDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VisitPlaceResponsePDB) GetPlaceName() string {
	if m != nil {
		return m.PlaceName
	}
	return ""
}

func (m *VisitPlaceResponsePDB) GetPlaceCity() string {
	if m != nil {
		return m.PlaceCity
	}
	return ""
}

func (m *VisitPlaceResponsePDB) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type VisitedPlacesRequestPDB struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitedPlacesRequestPDB) Reset()         { *m = VisitedPlacesRequestPDB{} }
func (m *VisitedPlacesRequestPDB) String() string { return proto.CompactTextString(m) }
func (*VisitedPlacesRequestPDB) ProtoMessage()    {}
func (*VisitedPlacesRequestPDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{22}
}

func (m *VisitedPlacesRequestPDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitedPlacesRequestPDB.Unmarshal(m, b)
}
func (m *VisitedPlacesRequestPDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitedPlacesRequestPDB.Marshal(b, m, deterministic)
}
func (m *VisitedPlacesRequestPDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitedPlacesRequestPDB.Merge(m, src)
}
func (m *VisitedPlacesRequestPDB) XXX_Size() int {
	return xxx_messageInfo_VisitedPlacesRequestPDB.Size(m)
}
func (m *VisitedPlacesRequestPDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitedPlacesRequestPDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitedPlacesRequestPDB proto.InternalMessageInfo

func (m *VisitedPlacesRequestPDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type VisitedPlacesResponsePDB struct {
	Email                string      `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Places               []*PlacePDB `protobuf:"bytes,2,rep,name=places,proto3" json:"places,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VisitedPlacesResponsePDB) Reset()         { *m = VisitedPlacesResponsePDB{} }
func (m *VisitedPlacesResponsePDB) String() string { return proto.CompactTextString(m) }
func (*VisitedPlacesResponsePDB) ProtoMessage()    {}
func (*VisitedPlacesResponsePDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8a164433363f89, []int{23}
}

func (m *VisitedPlacesResponsePDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitedPlacesResponsePDB.Unmarshal(m, b)
}
func (m *VisitedPlacesResponsePDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitedPlacesResponsePDB.Marshal(b, m, deterministic)
}
func (m *VisitedPlacesResponsePDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitedPlacesResponsePDB.Merge(m, src)
}
func (m *VisitedPlacesResponsePDB) XXX_Size() int {
	return xxx_messageInfo_VisitedPlacesResponsePDB.Size(m)
}
func (m *VisitedPlacesResponsePDB) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitedPlacesResponsePDB.DiscardUnknown(m)
}

var xxx_messageInfo_VisitedPlacesResponsePDB proto.InternalMessageInfo

func (m *VisitedPlacesResponsePDB) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VisitedPlacesResponsePDB) GetPlaces() []*PlacePDB {
	if m != nil {
		return m.Places
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequestPDB)(nil), "wcity.CreateUserRequestPDB")
	proto.RegisterType((*CreateUserResponsePDB)(nil), "wcity.CreateUserResponsePDB")
	proto.RegisterType((*GetUserRequestPDB)(nil), "wcity.GetUserRequestPDB")
	proto.RegisterType((*UserResponsePDB)(nil), "wcity.UserResponsePDB")
	proto.RegisterType((*CityMinPDB)(nil), "wcity.CityMinPDB")
	proto.RegisterType((*CityPDB)(nil), "wcity.CityPDB")
	proto.RegisterType((*CityRequestPDB)(nil), "wcity.CityRequestPDB")
	proto.RegisterType((*CityResponsePDB)(nil), "wcity.CityResponsePDB")
	proto.RegisterType((*GeolocationPDB)(nil), "wcity.GeolocationPDB")
	proto.RegisterType((*PlaceMinPDB)(nil), "wcity.PlaceMinPDB")
	proto.RegisterType((*PlacePDB)(nil), "wcity.PlacePDB")
	proto.RegisterType((*PlaceRequestPDB)(nil), "wcity.PlaceRequestPDB")
	proto.RegisterType((*PlaceResponsePDB)(nil), "wcity.PlaceResponsePDB")
	proto.RegisterType((*UpdatedUserRequestPDB)(nil), "wcity.UpdatedUserRequestPDB")
	proto.RegisterType((*VisitedCitysRequestPDB)(nil), "wcity.VisitedCitysRequestPDB")
	proto.RegisterType((*VisitedCitysResponsePDB)(nil), "wcity.VisitedCitysResponsePDB")
	proto.RegisterType((*VisitCityRequestPDB)(nil), "wcity.VisitCityRequestPDB")
	proto.RegisterType((*VisitCityResponsePDB)(nil), "wcity.VisitCityResponsePDB")
	proto.RegisterType((*CityPlacesRequestPDB)(nil), "wcity.CityPlacesRequestPDB")
	proto.RegisterType((*CityPlacesResponsePDB)(nil), "wcity.CityPlacesResponsePDB")
	proto.RegisterType((*VisitPlaceRequestPDB)(nil), "wcity.VisitPlaceRequestPDB")
	proto.RegisterType((*VisitPlaceResponsePDB)(nil), "wcity.VisitPlaceResponsePDB")
	proto.RegisterType((*VisitedPlacesRequestPDB)(nil), "wcity.VisitedPlacesRequestPDB")
	proto.RegisterType((*VisitedPlacesResponsePDB)(nil), "wcity.VisitedPlacesResponsePDB")
}

func init() { proto.RegisterFile("profilesdb.proto", fileDescriptor_ff8a164433363f89) }

var fileDescriptor_ff8a164433363f89 = []byte{
	// 872 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0xfa, 0xb7, 0xee, 0x74, 0xac, 0x9d, 0x59, 0xbb, 0x28, 0x1b, 0x30, 0x59, 0x20, 0x06,
	0x17, 0x45, 0x6c, 0x43, 0x9a, 0x34, 0xb1, 0x8b, 0x75, 0xd3, 0xc4, 0x05, 0x53, 0x55, 0x18, 0x12,
	0x17, 0x20, 0x65, 0xa9, 0x81, 0x48, 0x5d, 0x53, 0x92, 0x6c, 0x68, 0xe2, 0x02, 0x6e, 0x78, 0x03,
	0x9e, 0x80, 0x17, 0xe0, 0x4d, 0x78, 0x02, 0x1e, 0x06, 0xdb, 0x71, 0x63, 0xc7, 0x49, 0xd6, 0x8d,
	0xaa, 0x77, 0xf1, 0x39, 0x3e, 0x3f, 0xdf, 0xf1, 0x77, 0x8e, 0x1d, 0x68, 0x8c, 0x7c, 0xef, 0x83,
	0x3b, 0x20, 0x41, 0xff, 0xb4, 0x4d, 0x3f, 0x43, 0x0f, 0x95, 0xbf, 0x38, 0x6e, 0x78, 0x89, 0x4f,
	0x61, 0xb9, 0xe3, 0x13, 0x3b, 0x24, 0x27, 0x01, 0xf1, 0x7b, 0xe4, 0xf3, 0x39, 0x09, 0xc2, 0xee,
	0xc1, 0x3e, 0x5a, 0x86, 0x32, 0x39, 0xb3, 0xdd, 0x81, 0x69, 0xac, 0x1b, 0x1b, 0xf3, 0xbd, 0x68,
	0x81, 0x10, 0x94, 0x86, 0xf6, 0x19, 0x31, 0x0b, 0x5c, 0xc8, 0xbf, 0xd1, 0x3a, 0xd4, 0xfa, 0x24,
	0x70, 0x7c, 0x77, 0x14, 0xba, 0xde, 0xd0, 0x2c, 0x72, 0x95, 0x2a, 0xc2, 0x87, 0xd0, 0x54, 0x63,
	0x04, 0x23, 0x6f, 0x18, 0x90, 0xfc, 0x20, 0x2d, 0xa8, 0x5c, 0xd8, 0x03, 0x97, 0xf4, 0x45, 0x18,
	0xb1, 0xc2, 0x8f, 0x60, 0xe9, 0x88, 0x84, 0x79, 0x79, 0x16, 0x14, 0x17, 0xf8, 0x8f, 0x01, 0xf5,
	0xeb, 0x05, 0xfb, 0x2f, 0x44, 0xe8, 0x19, 0x2c, 0x5c, 0xb8, 0x81, 0x1b, 0x92, 0x7e, 0x87, 0x16,
	0x31, 0x30, 0x4b, 0xeb, 0xc5, 0x8d, 0xda, 0xe6, 0x52, 0x9b, 0xd7, 0xb4, 0xcd, 0x64, 0x2f, 0xdd,
	0x21, 0x0d, 0xda, 0x4b, 0x6c, 0x43, 0x3b, 0x70, 0x4b, 0xac, 0xbb, 0x03, 0xdb, 0x21, 0x81, 0x59,
	0xe6, 0x76, 0x48, 0xd8, 0x71, 0xa1, 0x30, 0x4c, 0x6e, 0xc4, 0xef, 0x01, 0xa4, 0xd7, 0x38, 0x69,
	0x43, 0x49, 0xda, 0x84, 0x39, 0xc7, 0x3b, 0x1f, 0x86, 0xfe, 0xa5, 0xc0, 0x32, 0x5e, 0x22, 0x0c,
	0x0b, 0x0e, 0x2b, 0xbf, 0xe7, 0x1f, 0x72, 0xfc, 0x11, 0x9e, 0x84, 0x0c, 0xff, 0x35, 0x60, 0x8e,
	0x05, 0x98, 0x89, 0x77, 0xf4, 0x14, 0xaa, 0x03, 0xcf, 0xb1, 0x79, 0x35, 0x4b, 0x54, 0x5f, 0xdb,
	0x6c, 0x0a, 0xc8, 0x47, 0xc4, 0x1b, 0x6b, 0x18, 0xea, 0x78, 0x9b, 0x7e, 0x06, 0xe5, 0xf4, 0x19,
	0x3c, 0x86, 0xca, 0x28, 0xaa, 0x62, 0x25, 0xb7, 0x8a, 0x62, 0x07, 0xde, 0x83, 0x45, 0x86, 0x4e,
	0xe1, 0xcd, 0x8d, 0x40, 0xe2, 0x4b, 0xa8, 0x47, 0xf6, 0x92, 0x4e, 0x37, 0xab, 0x12, 0x25, 0x1f,
	0x63, 0x71, 0x9f, 0x97, 0xa7, 0xda, 0x8b, 0x16, 0xb4, 0x76, 0x25, 0x96, 0xb2, 0xa8, 0xc9, 0xa2,
	0x42, 0x1f, 0x96, 0x3c, 0xd7, 0xe1, 0x6d, 0x58, 0x4c, 0x16, 0x09, 0x35, 0xa0, 0x38, 0xa0, 0x25,
	0x61, 0x81, 0x0b, 0x3d, 0xf6, 0xc9, 0x25, 0x76, 0xc8, 0x63, 0x32, 0x89, 0x1d, 0xe2, 0x77, 0x50,
	0x53, 0xea, 0x90, 0x99, 0x2c, 0x6d, 0x33, 0x16, 0xe0, 0xc5, 0xc1, 0xb8, 0xcd, 0xa2, 0xd5, 0xb5,
	0xe8, 0xf2, 0xdb, 0x80, 0x2a, 0xf7, 0x3f, 0x03, 0xe7, 0x33, 0x61, 0x0b, 0x7e, 0x0e, 0x75, 0x9e,
	0xf0, 0x04, 0x0a, 0xe4, 0xe4, 0x8d, 0xbf, 0x42, 0x43, 0x98, 0x5f, 0xcd, 0x80, 0x3c, 0xdc, 0xd9,
	0xe7, 0xff, 0x00, 0xca, 0x9c, 0xa0, 0x02, 0x66, 0x5d, 0x65, 0x30, 0x03, 0x18, 0x69, 0xb1, 0x03,
	0xcd, 0x93, 0x51, 0x9f, 0xce, 0xcf, 0xfe, 0x0c, 0x87, 0x74, 0x1b, 0x5a, 0x6f, 0x94, 0x59, 0x35,
	0x29, 0x0a, 0x3e, 0x81, 0x95, 0xe4, 0xfe, 0x49, 0x93, 0xf6, 0x3e, 0x94, 0x1d, 0x3e, 0x2c, 0x0b,
	0xbc, 0x5d, 0x75, 0xb6, 0x47, 0x4a, 0xec, 0xc2, 0x6d, 0xee, 0x56, 0x6b, 0xd7, 0x6c, 0x97, 0x16,
	0x54, 0x99, 0xd5, 0xb1, 0x44, 0x1b, 0xaf, 0x19, 0x62, 0xf6, 0xdd, 0x11, 0xfd, 0x28, 0x10, 0x2b,
	0x22, 0xfc, 0xdd, 0x80, 0x65, 0x25, 0xd6, 0xa4, 0xfc, 0xa7, 0x0a, 0x26, 0x09, 0x50, 0x52, 0x08,
	0x80, 0x5f, 0xd3, 0xdb, 0x97, 0xe1, 0xe7, 0x53, 0x4a, 0x81, 0xab, 0xc6, 0x32, 0xae, 0x8e, 0x55,
	0x48, 0x03, 0xfb, 0x69, 0xd0, 0x0b, 0x57, 0x71, 0x2b, 0x91, 0x4d, 0xe5, 0x37, 0x87, 0xc4, 0x0f,
	0xe3, 0x39, 0x1c, 0xdd, 0x82, 0x29, 0x16, 0x8f, 0x87, 0xf0, 0x27, 0x51, 0x6e, 0xbd, 0x0f, 0xb3,
	0xcb, 0xbd, 0x06, 0xf3, 0xdc, 0x4e, 0xa9, 0xb7, 0x14, 0xc4, 0x5a, 0x06, 0x53, 0x94, 0x5b, 0x0a,
	0xf0, 0x37, 0x68, 0xaa, 0x91, 0x26, 0x9d, 0xec, 0x14, 0xa1, 0x72, 0xce, 0xf5, 0x49, 0xdc, 0x1c,
	0xa9, 0xa3, 0xcd, 0xee, 0xa6, 0xb7, 0x60, 0x6a, 0x06, 0x93, 0x92, 0x96, 0x65, 0x2f, 0x5c, 0x59,
	0xf6, 0xcd, 0x1f, 0x15, 0x80, 0xae, 0x78, 0xfd, 0x51, 0x6f, 0x47, 0xf4, 0x25, 0x11, 0x3f, 0xc6,
	0xd0, 0xea, 0xb8, 0x0b, 0x33, 0xde, 0x80, 0xd6, 0x5a, 0x86, 0x52, 0xa6, 0xb5, 0x0b, 0x73, 0xe2,
	0x39, 0x86, 0xcc, 0x78, 0x3e, 0x6b, 0xcf, 0x33, 0xab, 0x25, 0x34, 0xba, 0xf1, 0xf6, 0x38, 0x0b,
	0x5e, 0x44, 0x6d, 0x16, 0xc4, 0x56, 0x7a, 0x63, 0xee, 0x01, 0x8a, 0xac, 0x54, 0x0a, 0x21, 0x1d,
	0xb9, 0xb5, 0xa2, 0x0a, 0x54, 0xfb, 0x1d, 0x9e, 0x32, 0x0f, 0xd9, 0x4c, 0x84, 0x48, 0xe5, 0xab,
	0x47, 0xde, 0x85, 0x2a, 0xb5, 0xe4, 0x0e, 0x51, 0x2b, 0xe9, 0x3e, 0xb6, 0xcd, 0x0d, 0x7b, 0x00,
	0xf3, 0xf1, 0x9c, 0x41, 0x96, 0xd8, 0x95, 0x31, 0xe5, 0xac, 0xd5, 0xb4, 0x4e, 0x7a, 0xa1, 0x07,
	0x27, 0x49, 0x8d, 0x12, 0x5b, 0xf5, 0x4c, 0xd6, 0x32, 0x94, 0xd2, 0x51, 0x17, 0xea, 0x14, 0x8b,
	0x3a, 0xbc, 0xd1, 0x1d, 0xd5, 0x20, 0x75, 0x03, 0x58, 0x77, 0x33, 0xd5, 0xd2, 0xe3, 0x2b, 0x68,
	0x48, 0x8f, 0x11, 0x81, 0x91, 0x66, 0xa3, 0xf7, 0x81, 0x75, 0x2f, 0x5b, 0x2f, 0x9d, 0x1e, 0xc3,
	0x52, 0x74, 0xeb, 0x29, 0x94, 0x9a, 0x82, 0xaf, 0xfb, 0x5b, 0x60, 0xba, 0x5e, 0xfb, 0xa3, 0x3f,
	0x72, 0xc4, 0xb6, 0x51, 0xdc, 0x14, 0xfb, 0x75, 0xd9, 0x20, 0x5d, 0xf6, 0x77, 0xd4, 0x35, 0x7e,
	0x15, 0x8a, 0xbd, 0x6e, 0xe7, 0xb4, 0xc2, 0x7f, 0x96, 0xb6, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x28, 0x01, 0x45, 0x7f, 0x40, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfilesDBClient is the client API for ProfilesDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfilesDBClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequestPDB, opts ...grpc.CallOption) (*CreateUserResponsePDB, error)
	GetUser(ctx context.Context, in *GetUserRequestPDB, opts ...grpc.CallOption) (*UserResponsePDB, error)
	CreateCity(ctx context.Context, in *CityPDB, opts ...grpc.CallOption) (*CityResponsePDB, error)
	CreatePlaceRequest(ctx context.Context, in *PlacePDB, opts ...grpc.CallOption) (*PlaceResponsePDB, error)
	GetCity(ctx context.Context, in *CityRequestPDB, opts ...grpc.CallOption) (*CityResponsePDB, error)
	GetPlace(ctx context.Context, in *PlaceRequestPDB, opts ...grpc.CallOption) (*PlaceResponsePDB, error)
	VisitCity(ctx context.Context, in *VisitCityRequestPDB, opts ...grpc.CallOption) (*VisitCityResponsePDB, error)
	VisitPlace(ctx context.Context, in *VisitPlaceRequestPDB, opts ...grpc.CallOption) (*VisitPlaceResponsePDB, error)
	GetVisitedCitys(ctx context.Context, in *VisitedCitysRequestPDB, opts ...grpc.CallOption) (*VisitedCitysResponsePDB, error)
	GetVisitedPlaces(ctx context.Context, in *VisitedPlacesRequestPDB, opts ...grpc.CallOption) (*VisitedPlacesResponsePDB, error)
	UpdateUserRequest(ctx context.Context, in *CreateUserRequestPDB, opts ...grpc.CallOption) (*CreateUserResponsePDB, error)
}

type profilesDBClient struct {
	cc *grpc.ClientConn
}

func NewProfilesDBClient(cc *grpc.ClientConn) ProfilesDBClient {
	return &profilesDBClient{cc}
}

func (c *profilesDBClient) CreateUser(ctx context.Context, in *CreateUserRequestPDB, opts ...grpc.CallOption) (*CreateUserResponsePDB, error) {
	out := new(CreateUserResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetUser(ctx context.Context, in *GetUserRequestPDB, opts ...grpc.CallOption) (*UserResponsePDB, error) {
	out := new(UserResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) CreateCity(ctx context.Context, in *CityPDB, opts ...grpc.CallOption) (*CityResponsePDB, error) {
	out := new(CityResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/CreateCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) CreatePlaceRequest(ctx context.Context, in *PlacePDB, opts ...grpc.CallOption) (*PlaceResponsePDB, error) {
	out := new(PlaceResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/CreatePlaceRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetCity(ctx context.Context, in *CityRequestPDB, opts ...grpc.CallOption) (*CityResponsePDB, error) {
	out := new(CityResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetPlace(ctx context.Context, in *PlaceRequestPDB, opts ...grpc.CallOption) (*PlaceResponsePDB, error) {
	out := new(PlaceResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) VisitCity(ctx context.Context, in *VisitCityRequestPDB, opts ...grpc.CallOption) (*VisitCityResponsePDB, error) {
	out := new(VisitCityResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/VisitCity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) VisitPlace(ctx context.Context, in *VisitPlaceRequestPDB, opts ...grpc.CallOption) (*VisitPlaceResponsePDB, error) {
	out := new(VisitPlaceResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/VisitPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetVisitedCitys(ctx context.Context, in *VisitedCitysRequestPDB, opts ...grpc.CallOption) (*VisitedCitysResponsePDB, error) {
	out := new(VisitedCitysResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetVisitedCitys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) GetVisitedPlaces(ctx context.Context, in *VisitedPlacesRequestPDB, opts ...grpc.CallOption) (*VisitedPlacesResponsePDB, error) {
	out := new(VisitedPlacesResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/GetVisitedPlaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profilesDBClient) UpdateUserRequest(ctx context.Context, in *CreateUserRequestPDB, opts ...grpc.CallOption) (*CreateUserResponsePDB, error) {
	out := new(CreateUserResponsePDB)
	err := c.cc.Invoke(ctx, "/wcity.ProfilesDB/UpdateUserRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfilesDBServer is the server API for ProfilesDB service.
type ProfilesDBServer interface {
	CreateUser(context.Context, *CreateUserRequestPDB) (*CreateUserResponsePDB, error)
	GetUser(context.Context, *GetUserRequestPDB) (*UserResponsePDB, error)
	CreateCity(context.Context, *CityPDB) (*CityResponsePDB, error)
	CreatePlaceRequest(context.Context, *PlacePDB) (*PlaceResponsePDB, error)
	GetCity(context.Context, *CityRequestPDB) (*CityResponsePDB, error)
	GetPlace(context.Context, *PlaceRequestPDB) (*PlaceResponsePDB, error)
	VisitCity(context.Context, *VisitCityRequestPDB) (*VisitCityResponsePDB, error)
	VisitPlace(context.Context, *VisitPlaceRequestPDB) (*VisitPlaceResponsePDB, error)
	GetVisitedCitys(context.Context, *VisitedCitysRequestPDB) (*VisitedCitysResponsePDB, error)
	GetVisitedPlaces(context.Context, *VisitedPlacesRequestPDB) (*VisitedPlacesResponsePDB, error)
	UpdateUserRequest(context.Context, *CreateUserRequestPDB) (*CreateUserResponsePDB, error)
}

// UnimplementedProfilesDBServer can be embedded to have forward compatible implementations.
type UnimplementedProfilesDBServer struct {
}

func (*UnimplementedProfilesDBServer) CreateUser(ctx context.Context, req *CreateUserRequestPDB) (*CreateUserResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedProfilesDBServer) GetUser(ctx context.Context, req *GetUserRequestPDB) (*UserResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedProfilesDBServer) CreateCity(ctx context.Context, req *CityPDB) (*CityResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCity not implemented")
}
func (*UnimplementedProfilesDBServer) CreatePlaceRequest(ctx context.Context, req *PlacePDB) (*PlaceResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlaceRequest not implemented")
}
func (*UnimplementedProfilesDBServer) GetCity(ctx context.Context, req *CityRequestPDB) (*CityResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCity not implemented")
}
func (*UnimplementedProfilesDBServer) GetPlace(ctx context.Context, req *PlaceRequestPDB) (*PlaceResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlace not implemented")
}
func (*UnimplementedProfilesDBServer) VisitCity(ctx context.Context, req *VisitCityRequestPDB) (*VisitCityResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitCity not implemented")
}
func (*UnimplementedProfilesDBServer) VisitPlace(ctx context.Context, req *VisitPlaceRequestPDB) (*VisitPlaceResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitPlace not implemented")
}
func (*UnimplementedProfilesDBServer) GetVisitedCitys(ctx context.Context, req *VisitedCitysRequestPDB) (*VisitedCitysResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitedCitys not implemented")
}
func (*UnimplementedProfilesDBServer) GetVisitedPlaces(ctx context.Context, req *VisitedPlacesRequestPDB) (*VisitedPlacesResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVisitedPlaces not implemented")
}
func (*UnimplementedProfilesDBServer) UpdateUserRequest(ctx context.Context, req *CreateUserRequestPDB) (*CreateUserResponsePDB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserRequest not implemented")
}

func RegisterProfilesDBServer(s *grpc.Server, srv ProfilesDBServer) {
	s.RegisterService(&_ProfilesDB_serviceDesc, srv)
}

func _ProfilesDB_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).CreateUser(ctx, req.(*CreateUserRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetUser(ctx, req.(*GetUserRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_CreateCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).CreateCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/CreateCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).CreateCity(ctx, req.(*CityPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_CreatePlaceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlacePDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).CreatePlaceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/CreatePlaceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).CreatePlaceRequest(ctx, req.(*PlacePDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetCity(ctx, req.(*CityRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetPlace(ctx, req.(*PlaceRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_VisitCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitCityRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).VisitCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/VisitCity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).VisitCity(ctx, req.(*VisitCityRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_VisitPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitPlaceRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).VisitPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/VisitPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).VisitPlace(ctx, req.(*VisitPlaceRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetVisitedCitys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitedCitysRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetVisitedCitys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetVisitedCitys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetVisitedCitys(ctx, req.(*VisitedCitysRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_GetVisitedPlaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitedPlacesRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).GetVisitedPlaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/GetVisitedPlaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).GetVisitedPlaces(ctx, req.(*VisitedPlacesRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfilesDB_UpdateUserRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequestPDB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfilesDBServer).UpdateUserRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wcity.ProfilesDB/UpdateUserRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfilesDBServer).UpdateUserRequest(ctx, req.(*CreateUserRequestPDB))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfilesDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wcity.ProfilesDB",
	HandlerType: (*ProfilesDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _ProfilesDB_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _ProfilesDB_GetUser_Handler,
		},
		{
			MethodName: "CreateCity",
			Handler:    _ProfilesDB_CreateCity_Handler,
		},
		{
			MethodName: "CreatePlaceRequest",
			Handler:    _ProfilesDB_CreatePlaceRequest_Handler,
		},
		{
			MethodName: "GetCity",
			Handler:    _ProfilesDB_GetCity_Handler,
		},
		{
			MethodName: "GetPlace",
			Handler:    _ProfilesDB_GetPlace_Handler,
		},
		{
			MethodName: "VisitCity",
			Handler:    _ProfilesDB_VisitCity_Handler,
		},
		{
			MethodName: "VisitPlace",
			Handler:    _ProfilesDB_VisitPlace_Handler,
		},
		{
			MethodName: "GetVisitedCitys",
			Handler:    _ProfilesDB_GetVisitedCitys_Handler,
		},
		{
			MethodName: "GetVisitedPlaces",
			Handler:    _ProfilesDB_GetVisitedPlaces_Handler,
		},
		{
			MethodName: "UpdateUserRequest",
			Handler:    _ProfilesDB_UpdateUserRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profilesdb.proto",
}
