// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profiles_shared.proto

package wcity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlaceOrCity int32

const (
	PlaceOrCity_CityType  PlaceOrCity = 0
	PlaceOrCity_PlaceType PlaceOrCity = 1
)

var PlaceOrCity_name = map[int32]string{
	0: "CityType",
	1: "PlaceType",
}

var PlaceOrCity_value = map[string]int32{
	"CityType":  0,
	"PlaceType": 1,
}

func (x PlaceOrCity) String() string {
	return proto.EnumName(PlaceOrCity_name, int32(x))
}

func (PlaceOrCity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{0}
}

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Descripiton          string   `protobuf:"bytes,3,opt,name=descripiton,proto3" json:"descripiton,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDescripiton() string {
	if m != nil {
		return m.Descripiton
	}
	return ""
}

func (m *User) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CityMin struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	CreatorEmail         string   `protobuf:"bytes,3,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityMin) Reset()         { *m = CityMin{} }
func (m *CityMin) String() string { return proto.CompactTextString(m) }
func (*CityMin) ProtoMessage()    {}
func (*CityMin) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{1}
}

func (m *CityMin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityMin.Unmarshal(m, b)
}
func (m *CityMin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityMin.Marshal(b, m, deterministic)
}
func (m *CityMin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityMin.Merge(m, src)
}
func (m *CityMin) XXX_Size() int {
	return xxx_messageInfo_CityMin.Size(m)
}
func (m *CityMin) XXX_DiscardUnknown() {
	xxx_messageInfo_CityMin.DiscardUnknown(m)
}

var xxx_messageInfo_CityMin proto.InternalMessageInfo

func (m *CityMin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CityMin) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CityMin) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

type Geolocation struct {
	Lon                  float32  `protobuf:"fixed32,1,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                  float32  `protobuf:"fixed32,2,opt,name=lat,proto3" json:"lat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Geolocation) Reset()         { *m = Geolocation{} }
func (m *Geolocation) String() string { return proto.CompactTextString(m) }
func (*Geolocation) ProtoMessage()    {}
func (*Geolocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{2}
}

func (m *Geolocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geolocation.Unmarshal(m, b)
}
func (m *Geolocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geolocation.Marshal(b, m, deterministic)
}
func (m *Geolocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geolocation.Merge(m, src)
}
func (m *Geolocation) XXX_Size() int {
	return xxx_messageInfo_Geolocation.Size(m)
}
func (m *Geolocation) XXX_DiscardUnknown() {
	xxx_messageInfo_Geolocation.DiscardUnknown(m)
}

var xxx_messageInfo_Geolocation proto.InternalMessageInfo

func (m *Geolocation) GetLon() float32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Geolocation) GetLat() float32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

type City struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Country              string       `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	CreatorEmail         string       `protobuf:"bytes,3,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	Location             *Geolocation `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Description          string       `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CityId               int32        `protobuf:"varint,6,opt,name=cityId,proto3" json:"cityId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{3}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *City) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *City) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

func (m *City) GetLocation() *Geolocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *City) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *City) GetCityId() int32 {
	if m != nil {
		return m.CityId
	}
	return 0
}

type PlaceMin struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country              string   `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	CreatorEmail         string   `protobuf:"bytes,4,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	PlaceId              int32    `protobuf:"varint,5,opt,name=placeId,proto3" json:"placeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceMin) Reset()         { *m = PlaceMin{} }
func (m *PlaceMin) String() string { return proto.CompactTextString(m) }
func (*PlaceMin) ProtoMessage()    {}
func (*PlaceMin) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{4}
}

func (m *PlaceMin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceMin.Unmarshal(m, b)
}
func (m *PlaceMin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceMin.Marshal(b, m, deterministic)
}
func (m *PlaceMin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceMin.Merge(m, src)
}
func (m *PlaceMin) XXX_Size() int {
	return xxx_messageInfo_PlaceMin.Size(m)
}
func (m *PlaceMin) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceMin.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceMin proto.InternalMessageInfo

func (m *PlaceMin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PlaceMin) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *PlaceMin) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *PlaceMin) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

func (m *PlaceMin) GetPlaceId() int32 {
	if m != nil {
		return m.PlaceId
	}
	return 0
}

type Place struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City                 string       `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country              string       `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	CreatorEmail         string       `protobuf:"bytes,4,opt,name=creatorEmail,proto3" json:"creatorEmail,omitempty"`
	Location             *Geolocation `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	Description          string       `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	PlaceId              int32        `protobuf:"varint,7,opt,name=placeId,proto3" json:"placeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}
func (*Place) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{5}
}

func (m *Place) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Place.Unmarshal(m, b)
}
func (m *Place) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Place.Marshal(b, m, deterministic)
}
func (m *Place) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Place.Merge(m, src)
}
func (m *Place) XXX_Size() int {
	return xxx_messageInfo_Place.Size(m)
}
func (m *Place) XXX_DiscardUnknown() {
	xxx_messageInfo_Place.DiscardUnknown(m)
}

var xxx_messageInfo_Place proto.InternalMessageInfo

func (m *Place) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Place) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Place) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Place) GetCreatorEmail() string {
	if m != nil {
		return m.CreatorEmail
	}
	return ""
}

func (m *Place) GetLocation() *Geolocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Place) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Place) GetPlaceId() int32 {
	if m != nil {
		return m.PlaceId
	}
	return 0
}

type SearchAllResult struct {
	Id                   int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 PlaceOrCity `protobuf:"varint,3,opt,name=type,proto3,enum=wcity.PlaceOrCity" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SearchAllResult) Reset()         { *m = SearchAllResult{} }
func (m *SearchAllResult) String() string { return proto.CompactTextString(m) }
func (*SearchAllResult) ProtoMessage()    {}
func (*SearchAllResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{6}
}

func (m *SearchAllResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAllResult.Unmarshal(m, b)
}
func (m *SearchAllResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAllResult.Marshal(b, m, deterministic)
}
func (m *SearchAllResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAllResult.Merge(m, src)
}
func (m *SearchAllResult) XXX_Size() int {
	return xxx_messageInfo_SearchAllResult.Size(m)
}
func (m *SearchAllResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAllResult.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAllResult proto.InternalMessageInfo

func (m *SearchAllResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchAllResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchAllResult) GetType() PlaceOrCity {
	if m != nil {
		return m.Type
	}
	return PlaceOrCity_CityType
}

type GetAllRequest struct {
	Max                  int32    `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{7}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

func (m *GetAllRequest) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type SearchAllRequest struct {
	Max                  int32    `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	Search               string   `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchAllRequest) Reset()         { *m = SearchAllRequest{} }
func (m *SearchAllRequest) String() string { return proto.CompactTextString(m) }
func (*SearchAllRequest) ProtoMessage()    {}
func (*SearchAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed978d8013990035, []int{8}
}

func (m *SearchAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchAllRequest.Unmarshal(m, b)
}
func (m *SearchAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchAllRequest.Marshal(b, m, deterministic)
}
func (m *SearchAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchAllRequest.Merge(m, src)
}
func (m *SearchAllRequest) XXX_Size() int {
	return xxx_messageInfo_SearchAllRequest.Size(m)
}
func (m *SearchAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchAllRequest proto.InternalMessageInfo

func (m *SearchAllRequest) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *SearchAllRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func init() {
	proto.RegisterEnum("wcity.PlaceOrCity", PlaceOrCity_name, PlaceOrCity_value)
	proto.RegisterType((*User)(nil), "wcity.User")
	proto.RegisterType((*CityMin)(nil), "wcity.CityMin")
	proto.RegisterType((*Geolocation)(nil), "wcity.Geolocation")
	proto.RegisterType((*City)(nil), "wcity.City")
	proto.RegisterType((*PlaceMin)(nil), "wcity.PlaceMin")
	proto.RegisterType((*Place)(nil), "wcity.Place")
	proto.RegisterType((*SearchAllResult)(nil), "wcity.SearchAllResult")
	proto.RegisterType((*GetAllRequest)(nil), "wcity.GetAllRequest")
	proto.RegisterType((*SearchAllRequest)(nil), "wcity.SearchAllRequest")
}

func init() { proto.RegisterFile("profiles_shared.proto", fileDescriptor_ed978d8013990035) }

var fileDescriptor_ed978d8013990035 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x94, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x86, 0x71, 0xb2, 0x4e, 0xd2, 0x49, 0x5b, 0x22, 0x03, 0xd5, 0x1e, 0x8b, 0x0f, 0x08, 0xf5,
	0xb0, 0x12, 0x20, 0x6e, 0x5c, 0x68, 0x85, 0x2a, 0x0e, 0x88, 0x95, 0x0b, 0x27, 0x84, 0x90, 0x71,
	0x0c, 0x35, 0x72, 0xe2, 0xc5, 0xeb, 0x08, 0xf2, 0x0a, 0x3c, 0x06, 0x8f, 0xc2, 0x5b, 0xf0, 0x36,
	0xd8, 0x93, 0xdd, 0xc8, 0x11, 0x2d, 0x12, 0x12, 0xe2, 0x94, 0x99, 0xf1, 0x78, 0xe6, 0x9b, 0x3f,
	0xde, 0x81, 0x3b, 0x8d, 0x77, 0x1f, 0x8c, 0xd5, 0xed, 0xbb, 0xf6, 0x52, 0x7a, 0x3d, 0xaf, 0xa2,
	0x1f, 0x1c, 0xa3, 0x5f, 0x94, 0x09, 0x6b, 0xfe, 0x09, 0x8a, 0xd7, 0xad, 0xf6, 0xec, 0x36, 0x50,
	0xbd, 0x90, 0xc6, 0x96, 0xe4, 0x98, 0xdc, 0xdf, 0x13, 0x1b, 0x87, 0x31, 0x28, 0x96, 0x72, 0xa1,
	0xcb, 0x01, 0x06, 0xd1, 0x66, 0xc7, 0x30, 0x9d, 0xeb, 0x56, 0x79, 0xd3, 0x98, 0xe0, 0x96, 0xe5,
	0x10, 0x8f, 0xf2, 0x10, 0x3b, 0x82, 0xd1, 0x2a, 0xd6, 0x7c, 0x3e, 0x2f, 0x8b, 0x78, 0x48, 0x45,
	0xe7, 0xf1, 0x37, 0x30, 0x3e, 0x8b, 0x3d, 0x5f, 0x98, 0xe5, 0xb6, 0x30, 0xc9, 0x0a, 0x97, 0x30,
	0x56, 0x6e, 0xb5, 0x0c, 0x7e, 0xdd, 0xf5, 0xeb, 0x5d, 0xc6, 0x61, 0x5f, 0x79, 0x2d, 0x83, 0xf3,
	0xcf, 0x90, 0x71, 0xd3, 0x73, 0x27, 0xc6, 0x1f, 0xc0, 0xf4, 0x5c, 0x3b, 0xeb, 0x94, 0x0c, 0x26,
	0x32, 0xcc, 0x60, 0x68, 0x23, 0x5d, 0xaa, 0x3f, 0x10, 0xc9, 0xc4, 0x88, 0x0c, 0x58, 0x3a, 0x45,
	0x64, 0xe0, 0x3f, 0x08, 0x14, 0x09, 0xe8, 0xdf, 0xd3, 0xb0, 0x0a, 0x26, 0x3d, 0x0a, 0x8a, 0x30,
	0x7d, 0xc8, 0x2a, 0x14, 0xbc, 0xca, 0x20, 0xc5, 0x36, 0x27, 0x13, 0x15, 0xaf, 0xd0, 0x1d, 0x51,
	0x31, 0x23, 0x8a, 0x9a, 0xee, 0x47, 0x51, 0x47, 0x1b, 0x51, 0x37, 0x1e, 0xff, 0x46, 0x60, 0x52,
	0x5b, 0xa9, 0xf4, 0x75, 0xb2, 0xc6, 0x58, 0x4a, 0xed, 0xff, 0xc3, 0x64, 0xe7, 0xc3, 0x0d, 0xff,
	0x3c, 0x5c, 0x71, 0xc5, 0x70, 0xf1, 0x76, 0x93, 0x3a, 0x46, 0x16, 0x8a, 0x2c, 0xbd, 0xcb, 0x7f,
	0x12, 0xa0, 0x08, 0xf3, 0x9f, 0x48, 0x72, 0x99, 0xe9, 0xdf, 0xcb, 0x3c, 0xfa, 0x5d, 0xe6, 0x6c,
	0xb6, 0xf1, 0xee, 0x6c, 0x6f, 0xe1, 0xe6, 0x85, 0x96, 0x5e, 0x5d, 0x3e, 0xb5, 0x56, 0xe8, 0x76,
	0x65, 0x03, 0x3b, 0x84, 0x81, 0x99, 0xe3, 0x88, 0x54, 0x44, 0xeb, 0xca, 0xcf, 0xe5, 0x1e, 0x14,
	0x61, 0xdd, 0x68, 0x9c, 0xee, 0x70, 0x8b, 0x87, 0x22, 0xbd, 0xf4, 0xe9, 0xf5, 0x09, 0x3c, 0xe7,
	0x77, 0xe1, 0xe0, 0x5c, 0x07, 0xac, 0xfd, 0x79, 0xa5, 0xdb, 0x90, 0xde, 0xeb, 0x42, 0x7e, 0xed,
	0xaa, 0x27, 0x93, 0x3f, 0x81, 0x59, 0x46, 0x70, 0x4d, 0x56, 0x7a, 0x28, 0x2d, 0x66, 0x75, 0x18,
	0x9d, 0x77, 0x72, 0x02, 0xd3, 0xac, 0x2b, 0xdb, 0x87, 0x49, 0xfa, 0x7d, 0x15, 0x7b, 0xcf, 0x6e,
	0xb0, 0x03, 0xd8, 0xc3, 0x43, 0x74, 0xc9, 0xe9, 0x63, 0x38, 0x32, 0xae, 0xfa, 0xe8, 0x1b, 0xd5,
	0xf1, 0xf6, 0x3b, 0xe4, 0xf4, 0x56, 0xdd, 0x59, 0x17, 0xb8, 0x4c, 0xea, 0xb4, 0x4b, 0x6a, 0xf2,
	0x7d, 0x30, 0x14, 0xf5, 0xd9, 0xfb, 0x11, 0xae, 0x96, 0x47, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xd2, 0x8c, 0xe1, 0xa5, 0x73, 0x04, 0x00, 0x00,
}
